USE GD2C2023
GO

IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'SQLSQUAD')
BEGIN 
	EXEC ('CREATE SCHEMA SQLSQUAD')
END
GO
/* 
 * TABLE: [SQLSQUAD.BI_Alquiler] 
 */

CREATE TABLE SQLSQUAD.BI_Alquiler(
    ALQUILER_TIEMPO_ID            numeric(18, 0)    NOT NULL,
    ALQUILER_COMISION             numeric(18, 2)    NULL,
    ALQUILER_UBICACION_ID         numeric(18, 0)    NOT NULL,
    ALQUILER_RANGO_M2_ID          numeric(18, 0)    NOT NULL,
    ALQUILER_TIPO_INMUEBLE_ID     numeric(18, 0)    NOT NULL,
    ALQUILER_TIPO_OPERACION_ID    numeric(18, 0)    NOT NULL,
    ALQUILER_TIPO_MONEDA_ID       numeric(18, 0)    NOT NULL,
    ALQUILER_AMBIENTES_ID         numeric(18, 0)    NOT NULL,
    ALQUILER_RANGO_ETARIO_ID      numeric(18, 0)    NOT NULL,
    ALQUILER_SUCURSAL_CODIGO      numeric(18, 0)    NOT NULL,
    PAGO_ID                       numeric(18, 0)    NOT NULL,
    CONSTRAINT PKALQ PRIMARY KEY NONCLUSTERED (ALQUILER_TIEMPO_ID, ALQUILER_UBICACION_ID, ALQUILER_RANGO_M2_ID, ALQUILER_TIPO_INMUEBLE_ID, ALQUILER_TIPO_OPERACION_ID, ALQUILER_TIPO_MONEDA_ID, ALQUILER_AMBIENTES_ID, ALQUILER_RANGO_ETARIO_ID, ALQUILER_SUCURSAL_CODIGO, PAGO_ID)
)
go



IF OBJECT_ID('SQLSQUAD.BI_Alquiler') IS NOT NULL
    PRINT '<<< CREATED TABLE SQLSQUAD.BI_Alquiler >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE SQLSQUAD.BI_Alquiler >>>'
go

/* 
 * TABLE: [SQLSQUAD.BI_Ambientes] 
 */

CREATE TABLE SQLSQUAD.BI_Ambientes(
    AMBIENTES_ID        numeric(18, 0)    IDENTITY(1,1),
    AMBIENTES_NOMBRE    nvarchar(100)     NULL,
    CONSTRAINT PKAMB PRIMARY KEY NONCLUSTERED (AMBIENTES_ID)
)
go



IF OBJECT_ID('SQLSQUAD.BI_Ambientes') IS NOT NULL
    PRINT '<<< CREATED TABLE SQLSQUAD.BI_Ambientes >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE SQLSQUAD.BI_Ambientes >>>'
go

/* 
 * TABLE: [SQLSQUAD.BI_Anuncio] 
 */

CREATE TABLE SQLSQUAD.BI_Anuncio(
    ANUNCIO_TIEMPO_ID            numeric(18, 0)    NOT NULL,
    ANUNCIO_DURACION_PROMEDIO    numeric(18, 0)    NULL,
    ANUNCIO_COSTO                numeric(18, 2)    NULL,
    ANUNCIO_AMBIENTES_ID         numeric(18, 0)    NOT NULL,
    ANUNCIO_UBICACION_ID         numeric(18, 0)    NOT NULL,
    ANUNCIO_TIPO_OPERACION_ID    numeric(18, 0)    NOT NULL,
    ANUNCIO_SUCURSAL_CODIGO      numeric(18, 0)    NOT NULL,
    ANUNCIO_TIPO_MONEDA_ID       numeric(18, 0)    NOT NULL,
    ANUNCIO_RANGO_M2_ID          numeric(18, 0)    NOT NULL,
    TIPO_INMUEBLE_ID             numeric(18, 0)    NOT NULL,
    ANUNCIO_RANGO_ETARIO_ID      numeric(18, 0)    NOT NULL,
    ESTADO_ANUNCIO_ID            numeric(18, 0)    NOT NULL,
    CONSTRAINT PKANU PRIMARY KEY NONCLUSTERED (ANUNCIO_TIEMPO_ID, ANUNCIO_AMBIENTES_ID, ANUNCIO_UBICACION_ID, ANUNCIO_TIPO_OPERACION_ID, ANUNCIO_SUCURSAL_CODIGO, ANUNCIO_TIPO_MONEDA_ID, ANUNCIO_RANGO_M2_ID, TIPO_INMUEBLE_ID, ANUNCIO_RANGO_ETARIO_ID, ESTADO_ANUNCIO_ID)
)
go



IF OBJECT_ID('SQLSQUAD.BI_Anuncio') IS NOT NULL
    PRINT '<<< CREATED TABLE SQLSQUAD.BI_Anuncio >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE SQLSQUAD.BI_Anuncio >>>'
go

/* 
 * TABLE: [SQLSQUAD.BI_Estado_Alquiler] 
 */

CREATE TABLE SQLSQUAD.BI_Estado_Alquiler(
    ESTADO_ALQUILER_ID        numeric(18, 0)    NULL,
    ESTADO_ALQUILER_NOMBRE    nvarchar(100)     NULL
)
go



IF OBJECT_ID('SQLSQUAD.BI_Estado_Alquiler') IS NOT NULL
    PRINT '<<< CREATED TABLE SQLSQUAD.BI_Estado_Alquiler >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE SQLSQUAD.BI_Estado_Alquiler >>>'
go

/* 
 * TABLE: [SQLSQUAD.BI_Estado_Anuncio] 
 */

CREATE TABLE SQLSQUAD.BI_Estado_Anuncio(
    ESTADO_ANUNCIO_ID        numeric(18, 0)    IDENTITY(1,1),
    ESTADO_ANUNCIO_NOMBRE    nvarchar(100)     NULL,
    CONSTRAINT PKEST_ANU PRIMARY KEY NONCLUSTERED (ESTADO_ANUNCIO_ID)
)
go



IF OBJECT_ID('SQLSQUAD.BI_Estado_Anuncio') IS NOT NULL
    PRINT '<<< CREATED TABLE SQLSQUAD.BI_Estado_Anuncio >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE SQLSQUAD.BI_Estado_Anuncio >>>'
go

/* 
 * TABLE: [SQLSQUAD.BI_Pago] 
 */

CREATE TABLE SQLSQUAD.BI_Pago(
    PAGO_ID                   numeric(18, 0)    IDENTITY(1,1),
    PAGO_IMPORTE              decimal(12, 2)    NULL,
    PAGO_FECHA_VENCIMIENTO    date              NULL,
    PAGO_FECHA                date              NULL,
    CONSTRAINT PKPAG PRIMARY KEY NONCLUSTERED (PAGO_ID)
)
go



IF OBJECT_ID('SQLSQUAD.BI_Pago') IS NOT NULL
    PRINT '<<< CREATED TABLE SQLSQUAD.BI_Pago >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE SQLSQUAD.BI_Pago >>>'
go

/* 
 * TABLE: [SQLSQUAD.BI_Rango_Etario] 
 */

CREATE TABLE SQLSQUAD.BI_Rango_Etario(
    RANGO_ETARIO_ID    numeric(18, 0)    NOT NULL,
    MENOR_A_25         bit               NULL,
    MAYOR_A_50         bit               NULL,
    ENTRE_35_Y_50      bit               NULL,
    ENTRE_25_Y_35      bit               NULL,
    CONSTRAINT PKRANG_ET PRIMARY KEY NONCLUSTERED (RANGO_ETARIO_ID)
)
go



IF OBJECT_ID('SQLSQUAD.BI_Rango_Etario') IS NOT NULL
    PRINT '<<< CREATED TABLE SQLSQUAD.BI_Rango_Etario >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE SQLSQUAD.BI_Rango_Etario >>>'
go

/* 
 * TABLE: [SQLSQUAD.BI_Rango_m2] 
 */

CREATE TABLE SQLSQUAD.BI_Rango_m2(
    RANGO_M2_ID       numeric(18, 0)    NOT NULL,
    MAYOR_A_100       bit               NULL,
    ENTRE_75_Y_100    bit               NULL,
    ENTRE_55_75       bit               NOT NULL,
    ENTRE_35_Y_55     bit               NULL,
    MENOR_A_35        bit               NULL,
    CONSTRAINT PKRANG_M2 PRIMARY KEY NONCLUSTERED (RANGO_M2_ID)
)
go



IF OBJECT_ID('SQLSQUAD.BI_Rango_m2') IS NOT NULL
    PRINT '<<< CREATED TABLE SQLSQUAD.BI_Rango_m2 >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE SQLSQUAD.BI_Rango_m2 >>>'
go

/* 
 * TABLE: [SQLSQUAD.BI_Sucursal] 
 */

CREATE TABLE SQLSQUAD.BI_Sucursal(
    SUCURSAL_CODIGO       numeric(18, 0)    IDENTITY(1,1),
    SUCURSAL_NOMBRE       nvarchar(100)     NULL,
    SUCURSAL_DIRECCION    nvarchar(100)     NULL,
    SUCURSAL_TELEFONO     nvarchar(100)     NULL,
    CONSTRAINT PKSUCU PRIMARY KEY NONCLUSTERED (SUCURSAL_CODIGO)
)
go



IF OBJECT_ID('SQLSQUAD.BI_Sucursal') IS NOT NULL
    PRINT '<<< CREATED TABLE SQLSQUAD.BI_Sucursal >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE SQLSQUAD.BI_Sucursal >>>'
go

/* 
 * TABLE: [SQLSQUAD.BI_Tiempo] 
 */

CREATE TABLE SQLSQUAD.BI_Tiempo(
    TIEMPO_ID              numeric(18, 0)    IDENTITY(1,1),
    TIEMPO_MES             int               NULL,
    TIEMPO_CUATRIMESTRE    int               NULL,
    TIEMPO_AÑO             int               NULL,
    TIEMPO_DIA             int               NULL,
    CONSTRAINT PKTIEM PRIMARY KEY NONCLUSTERED (TIEMPO_ID)
)
go



IF OBJECT_ID('SQLSQUAD.BI_Tiempo') IS NOT NULL
    PRINT '<<< CREATED TABLE SQLSQUAD.BI_Tiempo >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE SQLSQUAD.BI_Tiempo >>>'
go

/* 
 * TABLE: [SQLSQUAD.BI_Tipo_inmueble] 
 */

CREATE TABLE SQLSQUAD.BI_Tipo_inmueble(
    TIPO_INMUEBLE_ID        numeric(18, 0)    IDENTITY(1,1),
    TIPO_INMUEBLE_NOMBRE    nvarchar(100)     NULL,
    CONSTRAINT PKTIP_INM PRIMARY KEY NONCLUSTERED (TIPO_INMUEBLE_ID)
)
go



IF OBJECT_ID('SQLSQUAD.BI_Tipo_inmueble') IS NOT NULL
    PRINT '<<< CREATED TABLE SQLSQUAD.BI_Tipo_inmueble >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE SQLSQUAD.BI_Tipo_inmueble >>>'
go

/* 
 * TABLE: [SQLSQUAD.BI_Tipo_moneda] 
 */

CREATE TABLE SQLSQUAD.BI_Tipo_moneda(
    TIPO_MONEDA_ID        numeric(18, 0)    NOT NULL,
    TIPO_MONEDA_NOMBRE    nvarchar(100)     NULL,
    CONSTRAINT PK7TIP_MON PRIMARY KEY NONCLUSTERED (TIPO_MONEDA_ID)
)
go



IF OBJECT_ID('SQLSQUAD.BI_Tipo_moneda') IS NOT NULL
    PRINT '<<< CREATED TABLE SQLSQUAD.BI_Tipo_moneda >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE SQLSQUAD.BI_Tipo_moneda >>>'
go

/* 
 * TABLE: [SQLSQUAD.BI_Tipo_operacion] 
 */

CREATE TABLE SQLSQUAD.BI_Tipo_operacion(
    TIPO_OPERACION_ID        numeric(18, 0)    IDENTITY(1,1),
    TIPO_OPERACION_NOMBRE    nvarchar(100)     NULL,
    CONSTRAINT PK7_TIP_OP PRIMARY KEY NONCLUSTERED (TIPO_OPERACION_ID)
)
go



IF OBJECT_ID('SQLSQUAD.BI_Tipo_operacion') IS NOT NULL
    PRINT '<<< CREATED TABLE SQLSQUAD.BI_Tipo_operacion >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE SQLSQUAD.BI_Tipo_operacion >>>'
go

/* 
 * TABLE: [SQLSQUAD.BI_Ubicacion] 
 */

CREATE TABLE SQLSQUAD.BI_Ubicacion(
    UBICACION_ID            numeric(18, 0)    NOT NULL,
    UBICACION_BARRIO        nvarchar(100)     NULL,
    UBICACION_LOCALIDAD     nvarchar(100)     NULL,
    UBICACION_PROVINICIA    nvarchar(100)     NULL,
    CONSTRAINT PK4UBI PRIMARY KEY NONCLUSTERED (UBICACION_ID)
)
go



IF OBJECT_ID('SQLSQUAD.BI_Ubicacion') IS NOT NULL
    PRINT '<<< CREATED TABLE SQLSQUAD.BI_Ubicacion >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE SQLSQUAD.BI_Ubicacion >>>'
go

/* 
 * TABLE: [SQLSQUAD.BI_Venta_inmueble] 
 */

CREATE TABLE SQLSQUAD.BI_Venta_inmueble(
    TIEMPO_ID               numeric(18, 0)    NOT NULL,
    VENTA_PRECIO            numeric(18, 2)    NULL,
    VENTA_COMISION          numeric(18, 2)    NULL,
    VENTA_RANGO_M2_ID       numeric(18, 0)    NOT NULL,
    AMBIENTES_ID            numeric(18, 0)    NOT NULL,
    TIPO_OPERACION_ID       numeric(18, 0)    NOT NULL,
    VENTA_TIPO_MONEDA_ID    numeric(18, 0)    NOT NULL,
    TIPO_INMUEBLE_ID        numeric(18, 0)    NOT NULL,
    VENTA_UBICACION_ID      numeric(18, 0)    NOT NULL,
    SUCURSAL_CODIGO         numeric(18, 0)    NOT NULL,
    CONSTRAINT PK10VENT PRIMARY KEY NONCLUSTERED (TIEMPO_ID, VENTA_RANGO_M2_ID, AMBIENTES_ID, TIPO_OPERACION_ID, VENTA_TIPO_MONEDA_ID, TIPO_INMUEBLE_ID, VENTA_UBICACION_ID, SUCURSAL_CODIGO)
)
go



IF OBJECT_ID('SQLSQUAD.BI_Venta_inmueble') IS NOT NULL
    PRINT '<<< CREATED TABLE SQLSQUAD.BI_Venta_inmueble >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE SQLSQUAD.BI_Venta_inmueble >>>'
go

/* 
 * TABLE: [SQLSQUAD.BI_Alquiler] 
 */

ALTER TABLE SQLSQUAD.BI_Alquiler ADD CONSTRAINT [RefSQLSQUAD.BI_Tiempo10] 
    FOREIGN KEY (ALQUILER_TIEMPO_ID)
    REFERENCES SQLSQUAD.BI_Tiempo(TIEMPO_ID)
go

ALTER TABLE SQLSQUAD.BI_Alquiler ADD CONSTRAINT [RefSQLSQUAD.BI_Ubicacion11] 
    FOREIGN KEY (ALQUILER_UBICACION_ID)
    REFERENCES SQLSQUAD.BI_Ubicacion(UBICACION_ID)
go

ALTER TABLE SQLSQUAD.BI_Alquiler ADD CONSTRAINT [RefSQLSQUAD.BI_Rango_m212] 
    FOREIGN KEY (ALQUILER_RANGO_M2_ID)
    REFERENCES SQLSQUAD.BI_Rango_m2(RANGO_M2_ID)
go

ALTER TABLE SQLSQUAD.BI_Alquiler ADD CONSTRAINT [RefSQLSQUAD.BI_Tipo_inmueble13] 
    FOREIGN KEY (ALQUILER_TIPO_INMUEBLE_ID)
    REFERENCES SQLSQUAD.BI_Tipo_inmueble(TIPO_INMUEBLE_ID)
go

ALTER TABLE SQLSQUAD.BI_Alquiler ADD CONSTRAINT [RefSQLSQUAD.BI_Tipo_operacion14] 
    FOREIGN KEY (ALQUILER_TIPO_OPERACION_ID)
    REFERENCES SQLSQUAD.BI_Tipo_operacion(TIPO_OPERACION_ID)
go

ALTER TABLE SQLSQUAD.BI_Alquiler ADD CONSTRAINT [RefSQLSQUAD.BI_Tipo_moneda15] 
    FOREIGN KEY (ALQUILER_TIPO_MONEDA_ID)
    REFERENCES SQLSQUAD.BI_Tipo_moneda(TIPO_MONEDA_ID)
go

ALTER TABLE SQLSQUAD.BI_Alquiler ADD CONSTRAINT [RefSQLSQUAD.BI_Ambientes16] 
    FOREIGN KEY (ALQUILER_AMBIENTES_ID)
    REFERENCES SQLSQUAD.BI_Ambientes(AMBIENTES_ID)
go

ALTER TABLE SQLSQUAD.BI_Alquiler ADD CONSTRAINT [RefSQLSQUAD.BI_Rango_Etario17] 
    FOREIGN KEY (ALQUILER_RANGO_ETARIO_ID)
    REFERENCES SQLSQUAD.BI_Rango_Etario(RANGO_ETARIO_ID)
go

ALTER TABLE SQLSQUAD.BI_Alquiler ADD CONSTRAINT [RefSQLSQUAD.BI_Sucursal18] 
    FOREIGN KEY (ALQUILER_SUCURSAL_CODIGO)
    REFERENCES SQLSQUAD.BI_Sucursal(SUCURSAL_CODIGO)
go

ALTER TABLE SQLSQUAD.BI_Alquiler ADD CONSTRAINT [RefSQLSQUAD.BI_Pago28] 
    FOREIGN KEY (PAGO_ID)
    REFERENCES SQLSQUAD.BI_Pago(PAGO_ID)
go

/* 
 * TABLE: [SQLSQUAD.BI_Anuncio] 
 */

ALTER TABLE SQLSQUAD.BI_Anuncio ADD CONSTRAINT [RefSQLSQUAD.BI_Tiempo1] 
    FOREIGN KEY (ANUNCIO_TIEMPO_ID)
    REFERENCES SQLSQUAD.BI_Tiempo(TIEMPO_ID)
go

ALTER TABLE SQLSQUAD.BI_Anuncio ADD CONSTRAINT [RefSQLSQUAD.BI_Ambientes2] 
    FOREIGN KEY (ANUNCIO_AMBIENTES_ID)
    REFERENCES SQLSQUAD.BI_Ambientes(AMBIENTES_ID)
go

ALTER TABLE SQLSQUAD.BI_Anuncio ADD CONSTRAINT [RefSQLSQUAD.BI_Ubicacion3] 
    FOREIGN KEY (ANUNCIO_UBICACION_ID)
    REFERENCES SQLSQUAD.BI_Ubicacion(UBICACION_ID)
go

ALTER TABLE SQLSQUAD.BI_Anuncio ADD CONSTRAINT [RefSQLSQUAD.BI_Tipo_operacion4] 
    FOREIGN KEY (ANUNCIO_TIPO_OPERACION_ID)
    REFERENCES SQLSQUAD.BI_Tipo_operacion(TIPO_OPERACION_ID)
go

ALTER TABLE SQLSQUAD.BI_Anuncio ADD CONSTRAINT [RefSQLSQUAD.BI_Sucursal5] 
    FOREIGN KEY (ANUNCIO_SUCURSAL_CODIGO)
    REFERENCES SQLSQUAD.BI_Sucursal(SUCURSAL_CODIGO)
go

ALTER TABLE SQLSQUAD.BI_Anuncio ADD CONSTRAINT [RefSQLSQUAD.BI_Rango_Etario6] 
    FOREIGN KEY (ANUNCIO_RANGO_ETARIO_ID)
    REFERENCES SQLSQUAD.BI_Rango_Etario(RANGO_ETARIO_ID)
go

ALTER TABLE SQLSQUAD.BI_Anuncio ADD CONSTRAINT [RefSQLSQUAD.BI_Tipo_moneda7] 
    FOREIGN KEY (ANUNCIO_TIPO_MONEDA_ID)
    REFERENCES SQLSQUAD.BI_Tipo_moneda(TIPO_MONEDA_ID)
go

ALTER TABLE SQLSQUAD.BI_Anuncio ADD CONSTRAINT [RefSQLSQUAD.BI_Rango_m28] 
    FOREIGN KEY (ANUNCIO_RANGO_M2_ID)
    REFERENCES SQLSQUAD.BI_Rango_m2(RANGO_M2_ID)
go

ALTER TABLE SQLSQUAD.BI_Anuncio ADD CONSTRAINT [RefSQLSQUAD.BI_Tipo_inmueble9] 
    FOREIGN KEY (TIPO_INMUEBLE_ID)
    REFERENCES SQLSQUAD.BI_Tipo_inmueble(TIPO_INMUEBLE_ID)
go

ALTER TABLE SQLSQUAD.BI_Anuncio ADD CONSTRAINT [RefSQLSQUAD.BI_Estado_Anuncio30] 
    FOREIGN KEY (ESTADO_ANUNCIO_ID)
    REFERENCES SQLSQUAD.BI_Estado_Anuncio(ESTADO_ANUNCIO_ID)
go


/* 
 * TABLE: [SQLSQUAD.BI_Venta_inmueble] 
 */

ALTER TABLE SQLSQUAD.BI_Venta_inmueble ADD CONSTRAINT [RefSQLSQUAD.BI_Tiempo19] 
    FOREIGN KEY (TIEMPO_ID)
    REFERENCES SQLSQUAD.BI_Tiempo(TIEMPO_ID)
go

ALTER TABLE SQLSQUAD.BI_Venta_inmueble ADD CONSTRAINT [RefSQLSQUAD.BI_Rango_m220] 
    FOREIGN KEY (VENTA_RANGO_M2_ID)
    REFERENCES SQLSQUAD.BI_Rango_m2(RANGO_M2_ID)
go

ALTER TABLE SQLSQUAD.BI_Venta_inmueble ADD CONSTRAINT [RefSQLSQUAD.BI_Ambientes21] 
    FOREIGN KEY (AMBIENTES_ID)
    REFERENCES SQLSQUAD.BI_Ambientes(AMBIENTES_ID)
go

ALTER TABLE SQLSQUAD.BI_Venta_inmueble ADD CONSTRAINT [RefSQLSQUAD.BI_Tipo_operacion22] 
    FOREIGN KEY (TIPO_OPERACION_ID)
    REFERENCES SQLSQUAD.BI_Tipo_operacion(TIPO_OPERACION_ID)
go

ALTER TABLE SQLSQUAD.BI_Venta_inmueble ADD CONSTRAINT [RefSQLSQUAD.BI_Tipo_moneda23] 
    FOREIGN KEY (VENTA_TIPO_MONEDA_ID)
    REFERENCES SQLSQUAD.BI_Tipo_moneda(TIPO_MONEDA_ID)
go

ALTER TABLE SQLSQUAD.BI_Venta_inmueble ADD CONSTRAINT [RefSQLSQUAD.BI_Tipo_inmueble25] 
    FOREIGN KEY (TIPO_INMUEBLE_ID)
    REFERENCES SQLSQUAD.BI_Tipo_inmueble(TIPO_INMUEBLE_ID)
go

ALTER TABLE SQLSQUAD.BI_Venta_inmueble ADD CONSTRAINT [RefSQLSQUAD.BI_Ubicacion26] 
    FOREIGN KEY (VENTA_UBICACION_ID)
    REFERENCES SQLSQUAD.BI_Ubicacion(UBICACION_ID)
go

ALTER TABLE SQLSQUAD.BI_Venta_inmueble ADD CONSTRAINT [RefSQLSQUAD.BI_Sucursal27] 
    FOREIGN KEY (SUCURSAL_CODIGO)
    REFERENCES SQLSQUAD.BI_Sucursal(SUCURSAL_CODIGO)
go


