USE GD2C2023
GO

IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'SQLSQUAD')
BEGIN 
	EXEC ('CREATE SCHEMA SQLSQUAD')
END
GO

/* 
 * TABLE: SQLSQUAD.BI_Alquiler 
 */
 
CREATE TABLE SQLSQUAD.BI_Alquiler(
    BI_ALQUILER_TIEMPO_ID             numeric(18, 0)    NOT NULL,
    BI_ALQUILER_UBICACION_ID          numeric(18, 0)    NOT NULL,
    BI_ALQUILER_TIPO_INMUEBLE_ID      numeric(18, 0)    NOT NULL,
    BI_ALQUILER_TIPO_OPERACION_ID     numeric(18, 0)    NOT NULL,
    BI_ALQUILER_RANGO_ETARIO_ID       numeric(18, 0)    NOT NULL,
    BI_ALQUILER_SUCURSAL_CODIGO       numeric(18, 0)    NOT NULL,
    BI_ALQUILER_PAGO_ID               numeric(18, 0)    NOT NULL,
    BI_ALQUILER_ESTADO_ALQUILER_ID    numeric(18, 0)    NOT NULL,
    BI_ALQUILER_COMISION              numeric(18, 2)    NULL,
    CONSTRAINT PK_8 PRIMARY KEY NONCLUSTERED (BI_ALQUILER_TIEMPO_ID, BI_ALQUILER_UBICACION_ID, BI_ALQUILER_TIPO_INMUEBLE_ID, BI_ALQUILER_TIPO_OPERACION_ID, BI_ALQUILER_RANGO_ETARIO_ID, BI_ALQUILER_SUCURSAL_CODIGO, BI_ALQUILER_PAGO_ID, BI_ALQUILER_ESTADO_ALQUILER_ID)
)
GO



IF OBJECT_ID('SQLSQUAD.BI_Alquiler') IS NOT NULL
    PRINT '<<< CREATED TABLE SQLSQUAD.BI_Alquiler >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE SQLSQUAD.BI_Alquiler >>>'
GO

/* 
 * TABLE: SQLSQUAD.BI_Ambientes 
 */

CREATE TABLE SQLSQUAD.BI_Ambientes(
    BI_AMBIENTES_ID        numeric(18, 0)    NOT NULL,
    BI_AMBIENTES_NOMBRE    nvarchar(100)     NULL,
    CONSTRAINT PK_11 PRIMARY KEY NONCLUSTERED (BI_AMBIENTES_ID)
)
GO



IF OBJECT_ID('SQLSQUAD.BI_Ambientes') IS NOT NULL
    PRINT '<<< CREATED TABLE SQLSQUAD.BI_Ambientes >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE SQLSQUAD.BI_Ambientes >>>'
GO

/* 
 * TABLE: SQLSQUAD.BI_Anuncio 
 */

CREATE TABLE SQLSQUAD.BI_Anuncio(
    BI_ANUNCIO_TIEMPO_ID            numeric(18, 0)    NOT NULL,
    BI_ANUNCIO_AMBIENTES_ID         numeric(18, 0)    NOT NULL,
    BI_ANUNCIO_UBICACION_ID         numeric(18, 0)    NOT NULL,
    BI_ANUNCIO_TIPO_OPERACION_ID    numeric(18, 0)    NOT NULL,
    BI_ANUNCIO_SUCURSAL_CODIGO      numeric(18, 0)    NOT NULL,
    BI_ANUNCIO_TIPO_MONEDA_ID       numeric(18, 0)    NOT NULL,
    BI_ANUNCIO_RANGO_M2_ID          numeric(18, 0)    NOT NULL,
    BI_ANUNCIO_TIPO_INMUEBLE_ID     numeric(18, 0)    NOT NULL,
    BI_ANUNCIO_RANGO_ETARIO_ID      numeric(18, 0)    NOT NULL,
    BI_ANUNCIO_ESTADO_ANUNCIO_ID    numeric(18, 0)    NOT NULL,
    BI_ANUNCIO_DURACION             numeric(18, 0)    NULL,
    BI_ANUNCIO_COSTO                numeric(18, 2)    NULL,
    CONSTRAINT PK_1 PRIMARY KEY NONCLUSTERED (BI_ANUNCIO_TIEMPO_ID, BI_ANUNCIO_AMBIENTES_ID, BI_ANUNCIO_UBICACION_ID, BI_ANUNCIO_TIPO_OPERACION_ID, BI_ANUNCIO_SUCURSAL_CODIGO, BI_ANUNCIO_TIPO_MONEDA_ID, BI_ANUNCIO_RANGO_M2_ID, BI_ANUNCIO_TIPO_INMUEBLE_ID, BI_ANUNCIO_RANGO_ETARIO_ID, BI_ANUNCIO_ESTADO_ANUNCIO_ID)
)
GO



IF OBJECT_ID('SQLSQUAD.BI_Anuncio') IS NOT NULL
    PRINT '<<< CREATED TABLE SQLSQUAD.BI_Anuncio >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE SQLSQUAD.BI_Anuncio >>>'
GO

/* 
 * TABLE: SQLSQUAD.BI_Estado_alquiler 
 */

CREATE TABLE SQLSQUAD.BI_Estado_alquiler(
    BI_ESTADO_ALQUILER_ID        numeric(18, 0)    NOT NULL,
    BI_ESTADO_ALQUILER_NOMBRE    nvarchar(100)     NULL,
    CONSTRAINT PK_20 PRIMARY KEY CLUSTERED (BI_ESTADO_ALQUILER_ID)
)
GO



IF OBJECT_ID('SQLSQUAD.BI_Estado_alquiler') IS NOT NULL
    PRINT '<<< CREATED TABLE SQLSQUAD.BI_Estado_alquiler >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE SQLSQUAD.BI_Estado_alquiler >>>'
GO

/* 
 * TABLE: SQLSQUAD.BI_Estado_anuncio 
 */

CREATE TABLE SQLSQUAD.BI_Estado_anuncio(
    BI_ESTADO_ANUNCIO_ID        numeric(18, 0)    NOT NULL,
    BI_ESTADO_ANUNCIO_NOMBRE    nvarchar(100)     NULL,
    CONSTRAINT PK_21 PRIMARY KEY CLUSTERED (BI_ESTADO_ANUNCIO_ID)
)
GO



IF OBJECT_ID('SQLSQUAD.BI_Estado_anuncio') IS NOT NULL
    PRINT '<<< CREATED TABLE SQLSQUAD.BI_Estado_anuncio >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE SQLSQUAD.BI_Estado_anuncio >>>'
GO

/* 
 * TABLE: SQLSQUAD.BI_Pago 
 */

CREATE TABLE SQLSQUAD.BI_Pago(
    BI_PAGO_ID                   numeric(18, 0)    IDENTITY(1,1),
    BI_PAGO_IMPORTE              numeric(18, 2)    NULL,
    BI_PAGO_FECHA_VENCIMIENTO    datetime          NULL,
    BI_PAGO_FECHA                datetime          NULL,
    CONSTRAINT PK_19 PRIMARY KEY NONCLUSTERED (BI_PAGO_ID)
)
GO



IF OBJECT_ID('SQLSQUAD.BI_Pago') IS NOT NULL
    PRINT '<<< CREATED TABLE SQLSQUAD.BI_Pago >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE SQLSQUAD.BI_Pago >>>'
GO

/* 
 * TABLE: SQLSQUAD.BI_Rango_Etario 
 */

CREATE TABLE SQLSQUAD.BI_Rango_Etario(
    RANGO_ETARIO_ID    numeric(18, 0)    IDENTITY(1,1),
    MENOR_A_25         bit               NULL,
    MAYOR_A_50         bit               NULL,
    ENTRE_35_Y_50      bit               NULL,
    ENTRE_25_Y_35      bit               NULL,
    CONSTRAINT PK_6 PRIMARY KEY NONCLUSTERED (RANGO_ETARIO_ID)
)
GO



IF OBJECT_ID('SQLSQUAD.BI_Rango_Etario') IS NOT NULL
    PRINT '<<< CREATED TABLE SQLSQUAD.BI_Rango_Etario >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE SQLSQUAD.BI_Rango_Etario >>>'
GO

/* 
 * TABLE: SQLSQUAD.BI_Rango_m2 
 */

CREATE TABLE SQLSQUAD.BI_Rango_m2(
    RANGO_M2_ID       numeric(18, 0)    IDENTITY(1,1),
    MAYOR_A_100       bit               NULL,
    ENTRE_75_Y_100    bit               NULL,
    ENTRE_55_75       bit               NOT NULL,
    ENTRE_35_Y_55     bit               NULL,
    MENOR_A_35        bit               NULL,
    CONSTRAINT PK_13 PRIMARY KEY NONCLUSTERED (RANGO_M2_ID)
)
GO



IF OBJECT_ID('SQLSQUAD.BI_Rango_m2') IS NOT NULL
    PRINT '<<< CREATED TABLE SQLSQUAD.BI_Rango_m2 >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE SQLSQUAD.BI_Rango_m2 >>>'
GO

/* 
 * TABLE: SQLSQUAD.BI_Sucursal 
 */

CREATE TABLE SQLSQUAD.BI_Sucursal(
    BI_SUCURSAL_CODIGO       numeric(18, 0)    NOT NULL,
    BI_SUCURSAL_NOMBRE       nvarchar(100)     NULL,
    BI_SUCURSAL_DIRECCION    nvarchar(100)     NULL,
    BI_SUCURSAL_TELEFONO     nvarchar(100)     NULL,
    CONSTRAINT PK_5 PRIMARY KEY NONCLUSTERED (BI_SUCURSAL_CODIGO)
)
GO



IF OBJECT_ID('SQLSQUAD.BI_Sucursal') IS NOT NULL
    PRINT '<<< CREATED TABLE SQLSQUAD.BI_Sucursal >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE SQLSQUAD.BI_Sucursal >>>'
GO

/* 
 * TABLE: SQLSQUAD.BI_Tiempo 
 */

CREATE TABLE SQLSQUAD.BI_Tiempo(
    BI_TIEMPO_ID              numeric(18, 0)    IDENTITY(1,1),
    BI_TIEMPO_MES             int               NULL,
    BI_TIEMPO_CUATRIMESTRE    int               NULL,
    BI_TIEMPO_AÑO             int               NULL,
    CONSTRAINT PK_3 PRIMARY KEY NONCLUSTERED (BI_TIEMPO_ID)
)
GO



IF OBJECT_ID('SQLSQUAD.BI_Tiempo') IS NOT NULL
    PRINT '<<< CREATED TABLE SQLSQUAD.BI_Tiempo >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE SQLSQUAD.BI_Tiempo >>>'
GO

/* 
 * TABLE: SQLSQUAD.BI_Tipo_inmueble 
 */

CREATE TABLE SQLSQUAD.BI_Tipo_inmueble(
    BI_TIPO_INMUEBLE_ID        numeric(18, 0)    NOT NULL,
    BI_TIPO_INMUEBLE_NOMBRE    nvarchar(100)     NULL,
    CONSTRAINT PK_7 PRIMARY KEY NONCLUSTERED (BI_TIPO_INMUEBLE_ID)
)
GO



IF OBJECT_ID('SQLSQUAD.BI_Tipo_inmueble') IS NOT NULL
    PRINT '<<< CREATED TABLE SQLSQUAD.BI_Tipo_inmueble >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE SQLSQUAD.BI_Tipo_inmueble >>>'
GO

/* 
 * TABLE: SQLSQUAD.BI_Tipo_moneda 
 */

CREATE TABLE SQLSQUAD.BI_Tipo_moneda(
    BI_TIPO_MONEDA_ID        numeric(18, 0)    NOT NULL,
    BI_TIPO_MONEDA_NOMBRE    nvarchar(100)     NULL,
    CONSTRAINT PK_7_1_1 PRIMARY KEY NONCLUSTERED (BI_TIPO_MONEDA_ID)
)
GO



IF OBJECT_ID('SQLSQUAD.BI_Tipo_moneda') IS NOT NULL
    PRINT '<<< CREATED TABLE SQLSQUAD.BI_Tipo_moneda >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE SQLSQUAD.BI_Tipo_moneda >>>'
GO

/* 
 * TABLE: SQLSQUAD.BI_Tipo_operacion 
 */

CREATE TABLE SQLSQUAD.BI_Tipo_operacion(
    BI_TIPO_OPERACION_ID        numeric(18, 0)    NOT NULL,
    BI_TIPO_OPERACION_NOMBRE    nvarchar(100)     NULL,
    CONSTRAINT PK_7_1 PRIMARY KEY NONCLUSTERED (BI_TIPO_OPERACION_ID)
)
GO



IF OBJECT_ID('SQLSQUAD.BI_Tipo_operacion') IS NOT NULL
    PRINT '<<< CREATED TABLE SQLSQUAD.BI_Tipo_operacion >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE SQLSQUAD.BI_Tipo_operacion >>>'
GO

/* 
 * TABLE: SQLSQUAD.BI_Ubicacion 
 */

CREATE TABLE SQLSQUAD.BI_Ubicacion(
    BI_UBICACION_ID           numeric(18, 0)    IDENTITY(1,1),
    BI_UBICACION_BARRIO       nvarchar(100)     NULL,
    BI_UBICACION_LOCALIDAD    nvarchar(100)     NULL,
    BI_UBICACION_PROVINCIA    nvarchar(100)     NULL,
    CONSTRAINT PK_4 PRIMARY KEY NONCLUSTERED (BI_UBICACION_ID)
)
GO



IF OBJECT_ID('SQLSQUAD.BI_Ubicacion') IS NOT NULL
    PRINT '<<< CREATED TABLE SQLSQUAD.BI_Ubicacion >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE SQLSQUAD.BI_Ubicacion >>>'
GO

/* 
 * TABLE: SQLSQUAD.BI_Venta_inmueble 
 */

CREATE TABLE SQLSQUAD.BI_Venta_inmueble(
    BI_VENTA_TIEMPO_ID            numeric(18, 0)    NOT NULL,
    BI_VENTA_PRECIO               numeric(18, 2)    NULL,
    BI_VENTA_COMISION             numeric(18, 2)    NULL,
    BI_VENTA_RANGO_M2_ID          numeric(18, 0)    NOT NULL,
    BI_VENTA_TIPO_OPERACION_ID    numeric(18, 0)    NOT NULL,
    BI_VENTA_TIPO_MONEDA_ID       numeric(18, 0)    NOT NULL,
    BI_VENTA_TIPO_INMUEBLE_ID     numeric(18, 0)    NOT NULL,
    BI_VENTA_UBICACION_ID         numeric(18, 0)    NOT NULL,
    BI_VENTA_SUCURSAL_CODIGO      numeric(18, 0)    NOT NULL,
    CONSTRAINT PK_10 PRIMARY KEY NONCLUSTERED (BI_VENTA_TIEMPO_ID, BI_VENTA_RANGO_M2_ID, BI_VENTA_TIPO_OPERACION_ID, BI_VENTA_TIPO_MONEDA_ID, BI_VENTA_TIPO_INMUEBLE_ID, BI_VENTA_UBICACION_ID, BI_VENTA_SUCURSAL_CODIGO)
)
GO



IF OBJECT_ID('SQLSQUAD.BI_Venta_inmueble') IS NOT NULL
    PRINT '<<< CREATED TABLE SQLSQUAD.BI_Venta_inmueble >>>'
ELSE
    PRINT '<<< FAILED CREATING TABLE SQLSQUAD.BI_Venta_inmueble >>>'
GO

/* 
 * TABLE: SQLSQUAD.BI_Alquiler 
 */

ALTER TABLE SQLSQUAD.BI_Alquiler ADD CONSTRAINT RefBI_Tiempo101 
    FOREIGN KEY (BI_ALQUILER_TIEMPO_ID)
    REFERENCES SQLSQUAD.BI_Tiempo(BI_TIEMPO_ID)
GO

ALTER TABLE SQLSQUAD.BI_Alquiler ADD CONSTRAINT RefBI_Ubicacion111 
    FOREIGN KEY (BI_ALQUILER_UBICACION_ID)
    REFERENCES SQLSQUAD.BI_Ubicacion(BI_UBICACION_ID)
GO

ALTER TABLE SQLSQUAD.BI_Alquiler ADD CONSTRAINT RefBI_Tipo_inmueble131 
    FOREIGN KEY (BI_ALQUILER_TIPO_INMUEBLE_ID)
    REFERENCES SQLSQUAD.BI_Tipo_inmueble(BI_TIPO_INMUEBLE_ID)
GO

ALTER TABLE SQLSQUAD.BI_Alquiler ADD CONSTRAINT RefBI_Tipo_operacion141 
    FOREIGN KEY (BI_ALQUILER_TIPO_OPERACION_ID)
    REFERENCES SQLSQUAD.BI_Tipo_operacion(BI_TIPO_OPERACION_ID)
GO

ALTER TABLE SQLSQUAD.BI_Alquiler ADD CONSTRAINT RefBI_Rango_Etario171 
    FOREIGN KEY (BI_ALQUILER_RANGO_ETARIO_ID)
    REFERENCES SQLSQUAD.BI_Rango_Etario(RANGO_ETARIO_ID)
GO

ALTER TABLE SQLSQUAD.BI_Alquiler ADD CONSTRAINT RefBI_Sucursal181 
    FOREIGN KEY (BI_ALQUILER_SUCURSAL_CODIGO)
    REFERENCES SQLSQUAD.BI_Sucursal(BI_SUCURSAL_CODIGO)
GO

ALTER TABLE SQLSQUAD.BI_Alquiler ADD CONSTRAINT RefBI_Pago281 
    FOREIGN KEY (BI_ALQUILER_PAGO_ID)
    REFERENCES SQLSQUAD.BI_Pago(BI_PAGO_ID)
GO

ALTER TABLE SQLSQUAD.BI_Alquiler ADD CONSTRAINT RefBI_Estado_alquiler291 
    FOREIGN KEY (BI_ALQUILER_ESTADO_ALQUILER_ID)
    REFERENCES SQLSQUAD.BI_Estado_alquiler(BI_ESTADO_ALQUILER_ID)
GO


/* 
 * TABLE: SQLSQUAD.BI_Anuncio 
 */

ALTER TABLE SQLSQUAD.BI_Anuncio ADD CONSTRAINT RefBI_Tipo_moneda71 
    FOREIGN KEY (BI_ANUNCIO_TIPO_MONEDA_ID)
    REFERENCES SQLSQUAD.BI_Tipo_moneda(BI_TIPO_MONEDA_ID)
GO

ALTER TABLE SQLSQUAD.BI_Anuncio ADD CONSTRAINT RefBI_Rango_m281 
    FOREIGN KEY (BI_ANUNCIO_RANGO_M2_ID)
    REFERENCES SQLSQUAD.BI_Rango_m2(RANGO_M2_ID)
GO

ALTER TABLE SQLSQUAD.BI_Anuncio ADD CONSTRAINT RefBI_Tipo_inmueble91 
    FOREIGN KEY (BI_ANUNCIO_TIPO_INMUEBLE_ID)
    REFERENCES SQLSQUAD.BI_Tipo_inmueble(BI_TIPO_INMUEBLE_ID)
GO

ALTER TABLE SQLSQUAD.BI_Anuncio ADD CONSTRAINT RefBI_Tiempo11 
    FOREIGN KEY (BI_ANUNCIO_TIEMPO_ID)
    REFERENCES SQLSQUAD.BI_Tiempo(BI_TIEMPO_ID)
GO

ALTER TABLE SQLSQUAD.BI_Anuncio ADD CONSTRAINT RefBI_Ambientes21 
    FOREIGN KEY (BI_ANUNCIO_AMBIENTES_ID)
    REFERENCES SQLSQUAD.BI_Ambientes(BI_AMBIENTES_ID)
GO

ALTER TABLE SQLSQUAD.BI_Anuncio ADD CONSTRAINT RefBI_Ubicacion31 
    FOREIGN KEY (BI_ANUNCIO_UBICACION_ID)
    REFERENCES SQLSQUAD.BI_Ubicacion(BI_UBICACION_ID)
GO

ALTER TABLE SQLSQUAD.BI_Anuncio ADD CONSTRAINT RefBI_Tipo_operacion41 
    FOREIGN KEY (BI_ANUNCIO_TIPO_OPERACION_ID)
    REFERENCES SQLSQUAD.BI_Tipo_operacion(BI_TIPO_OPERACION_ID)
GO

ALTER TABLE SQLSQUAD.BI_Anuncio ADD CONSTRAINT RefBI_Sucursal51 
    FOREIGN KEY (BI_ANUNCIO_SUCURSAL_CODIGO)
    REFERENCES SQLSQUAD.BI_Sucursal(BI_SUCURSAL_CODIGO)
GO

ALTER TABLE SQLSQUAD.BI_Anuncio ADD CONSTRAINT RefBI_Rango_Etario61 
    FOREIGN KEY (BI_ANUNCIO_RANGO_ETARIO_ID)
    REFERENCES SQLSQUAD.BI_Rango_Etario(RANGO_ETARIO_ID)
GO

ALTER TABLE SQLSQUAD.BI_Anuncio ADD CONSTRAINT RefBI_Estado_anuncio301 
    FOREIGN KEY (BI_ANUNCIO_ESTADO_ANUNCIO_ID)
    REFERENCES SQLSQUAD.BI_Estado_anuncio(BI_ESTADO_ANUNCIO_ID)
GO


/* 
 * TABLE: SQLSQUAD.BI_Venta_inmueble 
 */

ALTER TABLE SQLSQUAD.BI_Venta_inmueble ADD CONSTRAINT RefBI_Tiempo191 
    FOREIGN KEY (BI_VENTA_TIEMPO_ID)
    REFERENCES SQLSQUAD.BI_Tiempo(BI_TIEMPO_ID)
GO

ALTER TABLE SQLSQUAD.BI_Venta_inmueble ADD CONSTRAINT RefBI_Rango_m2201 
    FOREIGN KEY (BI_VENTA_RANGO_M2_ID)
    REFERENCES SQLSQUAD.BI_Rango_m2(RANGO_M2_ID)
GO

ALTER TABLE SQLSQUAD.BI_Venta_inmueble ADD CONSTRAINT RefBI_Tipo_operacion221 
    FOREIGN KEY (BI_VENTA_TIPO_OPERACION_ID)
    REFERENCES SQLSQUAD.BI_Tipo_operacion(BI_TIPO_OPERACION_ID)
GO

ALTER TABLE SQLSQUAD.BI_Venta_inmueble ADD CONSTRAINT RefBI_Tipo_moneda231 
    FOREIGN KEY (BI_VENTA_TIPO_MONEDA_ID)
    REFERENCES SQLSQUAD.BI_Tipo_moneda(BI_TIPO_MONEDA_ID)
GO

ALTER TABLE SQLSQUAD.BI_Venta_inmueble ADD CONSTRAINT RefBI_Tipo_inmueble251 
    FOREIGN KEY (BI_VENTA_TIPO_INMUEBLE_ID)
    REFERENCES SQLSQUAD.BI_Tipo_inmueble(BI_TIPO_INMUEBLE_ID)
GO

ALTER TABLE SQLSQUAD.BI_Venta_inmueble ADD CONSTRAINT RefBI_Ubicacion261 
    FOREIGN KEY (BI_VENTA_UBICACION_ID)
    REFERENCES SQLSQUAD.BI_Ubicacion(BI_UBICACION_ID)
GO

ALTER TABLE SQLSQUAD.BI_Venta_inmueble ADD CONSTRAINT RefBI_Sucursal271 
    FOREIGN KEY (BI_VENTA_SUCURSAL_CODIGO)
    REFERENCES SQLSQUAD.BI_Sucursal(BI_SUCURSAL_CODIGO)
GO



-------------------------- FUNCIONES ----------------------------

CREATE FUNCTION SQLSQUAD.SignoMoneda(@moneda nvarchar(100))
RETURNS char(4)
AS
BEGIN
	 RETURN (SELECT CASE WHEN @moneda = 'Moneda Pesos' THEN '$'
						 WHEN @moneda = 'Moneda Dolares' THEN 'USD'
						 END)
END

GO
CREATE FUNCTION SQLSQUAD.noCumplioPago(@fecha_pago datetime, @fecha_vencimiento datetime)
RETURNS int
BEGIN
	 RETURN (SELECT CASE WHEN @fecha_vencimiento > @fecha_pago THEN 1
						 ELSE 0
						 END)
END

GO
CREATE FUNCTION SQLSQUAD.mayorA100(@superficie numeric(18,2))
RETURNS int
BEGIN
     IF @superficie > 100
		RETURN 1
	  
	 RETURN 0
END

GO
CREATE FUNCTION SQLSQUAD.entre75Y100(@superficie numeric(18,2))
RETURNS int
BEGIN
     IF @superficie >= 75 AND @superficie < 100
		RETURN 1
	  
	 RETURN 0
END

GO
CREATE FUNCTION SQLSQUAD.entre55Y75(@superficie numeric(18,2))
RETURNS int
BEGIN
     IF @superficie >= 55 AND @superficie < 75
		RETURN 1
	  
	 RETURN 0
END

GO
CREATE FUNCTION SQLSQUAD.entre35Y55(@superficie numeric(18,2))
RETURNS int
BEGIN
     IF @superficie >= 35 AND @superficie < 55
		RETURN 1
	  
	 RETURN 0
END
GO
CREATE FUNCTION SQLSQUAD.menorA35(@superficie numeric(18,2))
RETURNS int
BEGIN
     IF @superficie < 35
		RETURN 1
	  
	 RETURN 0
END
GO

CREATE FUNCTION SQLSQUAD.calcularEdad(@fechaNacimiento DATE)
RETURNS INT
AS
BEGIN
    DECLARE @edad INT;

    SELECT @edad = DATEDIFF(YEAR, @fechaNacimiento, GETDATE()) - 
                  CASE 
                     WHEN GETDATE() < DATEADD(YEAR, DATEDIFF(YEAR, @fechaNacimiento, GETDATE()), @fechaNacimiento) 
                     THEN 1 
                     ELSE 0 
                  END;

    RETURN @edad;
END

GO
CREATE FUNCTION SQLSQUAD.edadMenorA25(@edad int)
RETURNS int
BEGIN
	  IF @edad < 25
		RETURN 1
	  RETURN 0
END
GO
CREATE FUNCTION SQLSQUAD.edadEntre25Y35(@edad int)
RETURNS int
BEGIN
     IF @edad >= 25 AND @edad < 35
		RETURN 1
	 RETURN 0
END
GO
CREATE FUNCTION SQLSQUAD.edadEntre35Y50(@edad int)
RETURNS int
BEGIN
     IF @edad >= 35 AND @edad < 50
		RETURN 1
	  
	 RETURN 0
END
GO
CREATE FUNCTION SQLSQUAD.edadMayorA50(@edad int)
RETURNS int
BEGIN
     IF @edad >= 50
		RETURN 1
	  
	 RETURN 0
END
GO

CREATE FUNCTION SQLSQUAD.calcular_Rango_m2(@superficie numeric(18,2))
RETURNS int
BEGIN
	 RETURN (SELECT CASE WHEN SQLSQUAD.mayorA100(@superficie)   = 1  THEN 2
						 WHEN SQLSQUAD.entre75Y100(@superficie) = 1  THEN 5
						 WHEN SQLSQUAD.entre55Y75(@superficie)  = 1  THEN 4
						 WHEN SQLSQUAD.entre35Y55(@superficie)  = 1  THEN 3
						 WHEN SQLSQUAD.menorA35(@superficie)    = 1  THEN 1
						 END) 
END
GO
CREATE FUNCTION SQLSQUAD.calcular_Rango_etario(@edad int)
RETURNS int
BEGIN 
	 RETURN (SELECT CASE WHEN SQLSQUAD.edadMayorA50(@edad)    = 1  THEN 1
						 WHEN SQLSQUAD.edadEntre35Y50(@edad)  = 1  THEN 2
						 WHEN SQLSQUAD.edadEntre25Y35(@edad)  = 1  THEN 3
						 WHEN SQLSQUAD.edadMenorA25(@edad)    = 1  THEN 4
						 END) 
END
GO

-------------------------- PROCEDIMIENTOS ----------------------------

CREATE PROCEDURE MigrarDatosBI_Estado_Anuncio
AS 
BEGIN
	 INSERT INTO SQLSQUAD.BI_Estado_Anuncio(BI_ESTADO_ANUNCIO_ID, BI_ESTADO_ANUNCIO_NOMBRE)
	 SELECT E.ESTADO_ANUNCIO_ID, ESTADO_ANUNCIO_NOMBRE FROM SQLSQUAD.estado_anuncio E
END

GO
CREATE PROCEDURE MigrarDatosBI_Estado_Alquiler
AS 
BEGIN
	 INSERT INTO SQLSQUAD.BI_Estado_Alquiler(BI_ESTADO_ALQUILER_ID,BI_ESTADO_ALQUILER_NOMBRE)
	 SELECT E.ESTADO_ALQUILER_ID, E.ESTADO_ALQUILER_NOMBRE FROM SQLSQUAD.estado_alquiler E
END


CREATE PROCEDURE MigrarDatosBI_Rango_Etario
AS
BEGIN
	 INSERT INTO SQLSQUAD.BI_Rango_Etario(MENOR_A_25, ENTRE_25_Y_35, ENTRE_35_Y_50, MAYOR_A_50)
	 SELECT SQLSQUAD.edadMenorA25(SQLSQUAD.calcularEdad(INQUILINO_FECHA_NAC)), SQLSQUAD.edadEntre25Y35(SQLSQUAD.calcularEdad(INQUILINO_FECHA_NAC)), SQLSQUAD.edadEntre35Y50(SQLSQUAD.calcularEdad(INQUILINO_FECHA_NAC)), SQLSQUAD.edadMayorA50(SQLSQUAD.calcularEdad(INQUILINO_FECHA_NAC))
	 FROM SQLSQUAD.inquilino
	 UNION
	 SELECT SQLSQUAD.edadMenorA25(SQLSQUAD.calcularEdad(AGENTE_FECHA_NAC)), SQLSQUAD.edadEntre25Y35(SQLSQUAD.calcularEdad(AGENTE_FECHA_NAC)), SQLSQUAD.edadEntre35Y50(SQLSQUAD.calcularEdad(AGENTE_FECHA_NAC)), SQLSQUAD.edadMayorA50(SQLSQUAD.calcularEdad(AGENTE_FECHA_NAC))
	 FROM SQLSQUAD.agente
END

GO
CREATE PROCEDURE MigrarDatosBI_Sucursal
AS
BEGIN
	 INSERT INTO SQLSQUAD.BI_Sucursal(BI_SUCURSAL_CODIGO,BI_SUCURSAL_DIRECCION, BI_SUCURSAL_NOMBRE, BI_SUCURSAL_TELEFONO)
	 SELECT SUCURSAL_CODIGO,concat(concat(d.DIRECCION_CALLE, ' '),d.DIRECCION_NUMERO_CALLE), SUCURSAL_NOMBRE, SUCURSAL_TELEFONO
	 FROM SQLSQUAD.sucursal 
	 INNER JOIN SQLSQUAD.direccion d on d.DIRECCION_ID = sucursal.SUCURSAL_DIRECCION_ID 
END
GO
CREATE PROCEDURE MigrarDatosBI_Ubicacion
AS
BEGIN
	 INSERT INTO SQLSQUAD.BI_Ubicacion(BI_UBICACION_BARRIO, BI_UBICACION_LOCALIDAD, BI_UBICACION_PROVINCIA)
	 SELECT b.BARRIO_NOMBRE, l.LOCALIDAD_NOMBRE, p.PROVINCIA_NOMBRE
	 FROM SQLSQUAD.barrio b
	 INNER JOIN SQLSQUAD.localidad l on l.LOCALIDAD_ID = b.BARRIO_LOCALIDAD_ID
	 INNER JOIN SQLSQUAD.provincia p on p.PROVINCIA_ID = l.LOCALIDAD_PROVINCIA_ID
END

GO
CREATE PROCEDURE MigrarDatosBI_Tiempo
AS
BEGIN
    INSERT INTO SQLSQUAD.BI_Tiempo (BI_TIEMPO_MES, BI_TIEMPO_CUATRIMESTRE, BI_TIEMPO_AÑO)
    SELECT
        MONTH(ANUNCIO_FECHA_PUBLICACION) AS TIEMPO_MES,
        DATEPART(QUARTER, ANUNCIO_FECHA_PUBLICACION) AS TIEMPO_CUATRIMESTRE,
        YEAR(ANUNCIO_FECHA_PUBLICACION) AS TIEMPO_AÑO
    FROM SQLSQUAD.anuncio
	UNION
	SELECT
        MONTH(VENTA_FECHA) AS TIEMPO_MES,
        DATEPART(QUARTER, VENTA_FECHA) AS TIEMPO_CUATRIMESTRE,
        YEAR(VENTA_FECHA) AS TIEMPO_AÑO
    FROM SQLSQUAD.venta
END

GO
CREATE PROCEDURE MigrarDatosBI_Tipo_Operacion
AS
BEGIN
	INSERT INTO SQLSQUAD.BI_Tipo_Operacion(BI_TIPO_OPERACION_ID, BI_TIPO_OPERACION_NOMBRE)
    SELECT TIP_OP.TIPO_OPERACION_ID, TIP_OP.TIPO_OPERACION_NOMBRE
    FROM SQLSQUAD.tipo_operacion TIP_OP
END

GO
CREATE PROCEDURE MigrarDatosBI_Rango_m2
AS
BEGIN
	 INSERT INTO SQLSQUAD.BI_Rango_m2(MAYOR_A_100, ENTRE_75_Y_100, ENTRE_55_75, ENTRE_35_Y_55, MENOR_A_35)
	 SELECT DISTINCT SQLSQUAD.mayorA100(INMUEBLE_SUPERFICIETOTAL), SQLSQUAD.entre75Y100(INMUEBLE_SUPERFICIETOTAL), SQLSQUAD.entre55Y75(INMUEBLE_SUPERFICIETOTAL), SQLSQUAD.entre35Y55(INMUEBLE_SUPERFICIETOTAL), SQLSQUAD.menorA35(INMUEBLE_SUPERFICIETOTAL) FROM SQLSQUAD.inmueble
END

GO
CREATE PROCEDURE MigrarDatosBI_Tipo_Moneda
AS
BEGIN
	INSERT INTO SQLSQUAD.BI_Tipo_Moneda(BI_TIPO_MONEDA_ID, BI_TIPO_MONEDA_NOMBRE)
    SELECT  TIP_MON.MONEDA_ID, TIP_MON.MONEDA_NOMBRE
    FROM SQLSQUAD.moneda TIP_MON
END
GO
CREATE PROCEDURE MigrarDatosBI_Tipo_Inmueble
AS
BEGIN
	INSERT INTO SQLSQUAD.BI_Tipo_Inmueble(BI_TIPO_INMUEBLE_ID, BI_TIPO_INMUEBLE_NOMBRE)
    SELECT TIP_INM.TIPO_INMUEBLE_ID, TIP_INM.TIPO_INMUEBLE_NOMBRE
    FROM SQLSQUAD.tipo_inmueble TIP_INM
END
GO

CREATE PROCEDURE MigrarDatosBI_Ambientes
AS
BEGIN
	INSERT INTO SQLSQUAD.BI_Ambientes(BI_AMBIENTES_ID, BI_AMBIENTES_NOMBRE)
    SELECT C.CANT_AMBIENTES_ID, C.CANT_AMBIENTES_NOMBRE
    FROM SQLSQUAD.cant_ambientes C
END
GO

CREATE PROCEDURE MigrarDatosBI_Pago
AS 
BEGIN
	 INSERT INTO SQLSQUAD.BI_Pago(BI_PAGO_IMPORTE, BI_PAGO_FECHA, BI_PAGO_FECHA_VENCIMIENTO)
	 SELECT PAGO_ALQUILER_IMPORTE, PAGO_ALQUILER_FECHA, PAGO_ALQUILER_FECHA_VENCIMIENTO FROM SQLSQUAD.pago_alquiler
	 JOIN SQLSQUAD.alquiler ON PAGO_ALQUILER_ALQUILER_CODIGO = ALQUILER_CODIGO
	 GROUP BY PAGO_ALQUILER_IMPORTE, PAGO_ALQUILER_FECHA, PAGO_ALQUILER_FECHA_VENCIMIENTO
END
GO

CREATE PROCEDURE MigrarDatosBI_Anuncio_VERSION_NACHI
AS
BEGIN
	INSERT INTO SQLSQUAD.BI_Anuncio(BI_ANUNCIO_TIEMPO_ID, BI_ANUNCIO_AMBIENTES_ID, BI_ANUNCIO_UBICACION_ID, BI_ANUNCIO_TIPO_OPERACION_ID, BI_ANUNCIO_SUCURSAL_CODIGO, BI_ANUNCIO_TIPO_MONEDA_ID, BI_ANUNCIO_RANGO_M2_ID, BI_ANUNCIO_TIPO_INMUEBLE_ID, BI_ANUNCIO_RANGO_ETARIO_ID, BI_ANUNCIO_ESTADO_ANUNCIO_ID, BI_ANUNCIO_DURACION, BI_ANUNCIO_COSTO)
	SELECT BI_TIEMPO_ID, INMUEBLE_CANT_AMBIENTES_ID, BI_UBICACION_ID, ANUNCIO_TIPO_OPERACION_ID, AGENTE_SUCURSAL_CODIGO, ANUNCIO_MONEDA_ID, SQLSQUAD.calcular_Rango_m2(INMUEBLE_SUPERFICIETOTAL), INMUEBLE_TIPO_INMUEBLE_ID, SQLSQUAD.calcular_Rango_etario(SQLSQUAD.calcularEdad(AGENTE_FECHA_NAC)), BI_ESTADO_ANUNCIO_ID, AVG(DATEDIFF(DAY, ANUNCIO_FECHA_PUBLICACION, ANUNCIO_FECHA_FINALIZACION)), SUM(ANUNCIO_COSTO_ANUNCIO)
	FROM SQLSQUAD.anuncio
	JOIN SQLSQUAD.inmueble			ON ANUNCIO_INMUEBLE_CODIGO    = INMUEBLE_CODIGO
	JOIN SQLSQUAD.agente            ON ANUNCIO_AGENTE_CODIGO      = AGENTE_CODIGO
	JOIN SQLSQUAD.direccion			ON INMUEBLE_DIRECCION_ID      = DIRECCION_ID
	JOIN SQLSQUAD.barrio			ON DIRECCION_BARRIO_ID        = BARRIO_ID
	JOIN SQLSQUAD.localidad			ON BARRIO_LOCALIDAD_ID        = LOCALIDAD_ID
	JOIN SQLSQUAD.provincia			ON LOCALIDAD_PROVINCIA_ID     = PROVINCIA_ID
	JOIN SQLSQUAD.BI_Tiempo         ON (SELECT BI_TIEMPO_ID 
										 FROM SQLSQUAD.BI_Tiempo
										 WHERE BI_TIEMPO_AÑO 
										 = YEAR(ANUNCIO_FECHA_PUBLICACION) 
										AND BI_TIEMPO_CUATRIMESTRE =
										DATEPART(QUARTER, ANUNCIO_FECHA_PUBLICACION)
										AND BI_TIEMPO_MES 
										= MONTH(ANUNCIO_FECHA_PUBLICACION)) = BI_TIEMPO_ID
	JOIN SQLSQUAD.BI_Tipo_moneda    ON ANUNCIO_MONEDA_ID					= BI_TIPO_MONEDA_ID
	JOIN SQLSQUAD.BI_Ambientes      ON INMUEBLE_CANT_AMBIENTES_ID			= BI_AMBIENTES_ID
	JOIN SQLSQUAD.BI_Ubicacion      ON (SELECT BI_UBICACION_ID 
										FROM SQLSQUAD.BI_Ubicacion
										WHERE BARRIO_NOMBRE					= BI_UBICACION_BARRIO
										AND LOCALIDAD_NOMBRE				= BI_UBICACION_LOCALIDAD
										AND PROVINCIA_NOMBRE 
										= BI_UBICACION_PROVINCIA)			= BI_UBICACION_ID
	JOIN SQLSQUAD.BI_Tipo_operacion ON ANUNCIO_TIPO_OPERACION_ID			= BI_TIPO_OPERACION_ID
	JOIN SQLSQUAD.BI_Sucursal       ON AGENTE_SUCURSAL_CODIGO				= BI_SUCURSAL_CODIGO
	JOIN SQLSQUAD.BI_Estado_anuncio ON ANUNCIO_ESTADO_ANUNCIO_ID			= BI_ESTADO_ANUNCIO_ID
	JOIN SQLSQUAD.BI_Tipo_inmueble  ON INMUEBLE_TIPO_INMUEBLE_ID			= BI_TIPO_INMUEBLE_ID
	GROUP BY  BI_TIEMPO_ID, INMUEBLE_CANT_AMBIENTES_ID, BI_UBICACION_ID, ANUNCIO_TIPO_OPERACION_ID, AGENTE_SUCURSAL_CODIGO, ANUNCIO_MONEDA_ID, SQLSQUAD.calcular_Rango_m2(INMUEBLE_SUPERFICIETOTAL), INMUEBLE_TIPO_INMUEBLE_ID, SQLSQUAD.calcular_Rango_etario(SQLSQUAD.calcularEdad(AGENTE_FECHA_NAC)), BI_ESTADO_ANUNCIO_ID
    ORDER BY 1,2,3,4,5,6,7,8,9,10
				
END
GO

ALTER PROCEDURE MigrarDatosBI_Anuncio
AS
BEGIN
	INSERT INTO SQLSQUAD.BI_Anuncio(BI_ANUNCIO_TIEMPO_ID, BI_ANUNCIO_AMBIENTES_ID, BI_ANUNCIO_UBICACION_ID, BI_ANUNCIO_TIPO_OPERACION_ID, BI_ANUNCIO_SUCURSAL_CODIGO, BI_ANUNCIO_TIPO_MONEDA_ID, BI_ANUNCIO_RANGO_M2_ID, BI_ANUNCIO_TIPO_INMUEBLE_ID, BI_ANUNCIO_RANGO_ETARIO_ID, BI_ANUNCIO_ESTADO_ANUNCIO_ID, BI_ANUNCIO_DURACION, BI_ANUNCIO_COSTO)
	SELECT BI_TIEMPO_ID, INMUEBLE_CANT_AMBIENTES_ID, BI_UBICACION_ID, ANUNCIO_TIPO_OPERACION_ID, AGENTE_SUCURSAL_CODIGO, ANUNCIO_MONEDA_ID, SQLSQUAD.calcular_Rango_m2(INMUEBLE_SUPERFICIETOTAL), INMUEBLE_TIPO_INMUEBLE_ID, SQLSQUAD.calcular_Rango_etario(SQLSQUAD.calcularEdad(AGENTE_FECHA_NAC)), ANUNCIO_ESTADO_ANUNCIO_ID, AVG(DATEDIFF(DAY, ANUNCIO_FECHA_PUBLICACION, ANUNCIO_FECHA_FINALIZACION)), SUM(ANUNCIO_COSTO_ANUNCIO)
	FROM SQLSQUAD.anuncio
	JOIN SQLSQUAD.inmueble			ON ANUNCIO_INMUEBLE_CODIGO    = INMUEBLE_CODIGO
	JOIN SQLSQUAD.agente            ON ANUNCIO_AGENTE_CODIGO      = AGENTE_CODIGO
	JOIN SQLSQUAD.direccion			ON INMUEBLE_DIRECCION_ID      = DIRECCION_ID
	JOIN SQLSQUAD.barrio			ON DIRECCION_BARRIO_ID        = BARRIO_ID
	JOIN SQLSQUAD.localidad			ON BARRIO_LOCALIDAD_ID        = LOCALIDAD_ID
	JOIN SQLSQUAD.provincia			ON LOCALIDAD_PROVINCIA_ID     = PROVINCIA_ID
	JOIN SQLSQUAD.BI_Tiempo         ON (SELECT BI_TIEMPO_ID 
											 FROM SQLSQUAD.BI_Tiempo
											 WHERE BI_TIEMPO_AÑO        = YEAR(ANUNCIO_FECHA_PUBLICACION) 
											 AND BI_TIEMPO_CUATRIMESTRE = DATEPART(QUARTER, ANUNCIO_FECHA_PUBLICACION)
											 AND BI_TIEMPO_MES          = MONTH(ANUNCIO_FECHA_PUBLICACION)) = BI_TIEMPO_ID
	JOIN SQLSQUAD.BI_Ubicacion      ON (SELECT BI_UBICACION_ID 
											FROM SQLSQUAD.BI_Ubicacion
											WHERE BARRIO_NOMBRE	 = BI_UBICACION_BARRIO
											AND LOCALIDAD_NOMBRE = BI_UBICACION_LOCALIDAD
											AND PROVINCIA_NOMBRE = BI_UBICACION_PROVINCIA) = BI_UBICACION_ID
	GROUP BY  BI_TIEMPO_ID, INMUEBLE_CANT_AMBIENTES_ID, BI_UBICACION_ID, ANUNCIO_TIPO_OPERACION_ID, AGENTE_SUCURSAL_CODIGO, ANUNCIO_MONEDA_ID, SQLSQUAD.calcular_Rango_m2(INMUEBLE_SUPERFICIETOTAL), INMUEBLE_TIPO_INMUEBLE_ID, SQLSQUAD.calcular_Rango_etario(SQLSQUAD.calcularEdad(AGENTE_FECHA_NAC)), ANUNCIO_ESTADO_ANUNCIO_ID				
END
GO


--CREATE PROCEDURE MigrarDatosBI_Anuncio
--AS
--BEGIN
--	INSERT INTO SQLSQUAD.BI_Anuncio(BI_ANUNCIO_TIEMPO_ID, BI_ANUNCIO_AMBIENTES_ID, BI_ANUNCIO_UBICACION_ID, BI_ANUNCIO_TIPO_OPERACION_ID, BI_ANUNCIO_SUCURSAL_CODIGO, BI_ANUNCIO_TIPO_MONEDA_ID, BI_ANUNCIO_RANGO_M2_ID, BI_ANUNCIO_TIPO_INMUEBLE_ID, BI_ANUNCIO_RANGO_ETARIO_ID, BI_ANUNCIO_ESTADO_ANUNCIO, BI_ANUNCIO_DURACION, BI_ANUNCIO_COSTO)
--	SELECT (SELECT BI_TIEMPO_ID 
--				FROM SQLSQUAD.BI_Tiempo
--				WHERE BI_TIEMPO_AÑO = YEAR(ANUNCIO_FECHA_PUBLICACION) 
--				AND BI_TIEMPO_CUATRIMESTRE = DATEPART(QUARTER, ANUNCIO_FECHA_PUBLICACION)
--				AND BI_TIEMPO_MES = MONTH(ANUNCIO_FECHA_PUBLICACION)),
--			INMUEBLE_CANT_AMBIENTES_ID,
--		   (SELECT BI_UBICACION_ID 
--				FROM SQLSQUAD.BI_Ubicacion
--				WHERE BI_UBICACION_BARRIO = BARRIO_NOMBRE
--				AND BI_UBICACION_LOCALIDAD = LOCALIDAD_NOMBRE
--				AND BI_UBICACION_PROVINCIA = PROVINCIA_NOMBRE),
--			ANUNCIO_TIPO_OPERACION_ID,
--			AGENTE_SUCURSAL_CODIGO,
--			ANUNCIO_MONEDA_ID,
--			SQLSQUAD.calcular_Rango_m2(INMUEBLE_SUPERFICIETOTAL),
--			ANUNCIO_ESTADO_ANUNCIO_ID,
--			INMUEBLE_TIPO_INMUEBLE_ID,
--			SQLSQUAD.calcular_Rango_etario(SQLSQUAD.calcularEdad(AGENTE_FECHA_NAC)),
--			(SELECT ESTADO_ANUNCIO_NOMBRE FROM SQLSQUAD.estado_anuncio
--				WHERE ESTADO_ANUNCIO_ID = ANUNCIO_ESTADO_ANUNCIO_ID),
--			DATEDIFF(DAY, ANUNCIO_FECHA_PUBLICACION, ANUNCIO_FECHA_FINALIZACION),
--			ANUNCIO_COSTO_ANUNCIO
--	FROM SQLSQUAD.anuncio
--	JOIN SQLSQUAD.inmueble  ON ANUNCIO_INMUEBLE_CODIGO = INMUEBLE_CODIGO
--	JOIN SQLSQUAD.agente	ON ANUNCIO_AGENTE_CODIGO = AGENTE_CODIGO
--	JOIN SQLSQUAD.direccion ON INMUEBLE_DIRECCION_ID = DIRECCION_ID
--	JOIN SQLSQUAD.barrio	ON DIRECCION_BARRIO_ID = BARRIO_ID
--	JOIN SQLSQUAD.localidad ON BARRIO_LOCALIDAD_ID = LOCALIDAD_ID
--	JOIN SQLSQUAD.provincia ON LOCALIDAD_PROVINCIA_ID = PROVINCIA_ID
--	GROUP BY	YEAR(ANUNCIO_FECHA_PUBLICACION), 
--				DATEPART(QUARTER, ANUNCIO_FECHA_PUBLICACION), 
--				MONTH(ANUNCIO_FECHA_PUBLICACION), 
--				INMUEBLE_CANT_AMBIENTES_ID,
--				BARRIO_ID, BARRIO_NOMBRE,
--				LOCALIDAD_ID, LOCALIDAD_NOMBRE,
--				PROVINCIA_NOMBRE, PROVINCIA_NOMBRE,
--				ANUNCIO_TIPO_OPERACION_ID,
--				AGENTE_SUCURSAL_CODIGO,
--				ANUNCIO_MONEDA_ID,
--				SQLSQUAD.calcular_Rango_m2(INMUEBLE_SUPERFICIETOTAL),
--				INMUEBLE_TIPO_INMUEBLE_ID ,
--				SQLSQUAD.calcular_Rango_etario(SQLSQUAD.calcularEdad(AGENTE_FECHA_NAC)),
--				ANUNCIO_ESTADO_ANUNCIO_ID
--END
--GO

--CREATE PROCEDURE MigrarDatosBI_Alquiler
--AS
--BEGIN
--	INSERT INTO SQLSQUAD.BI_Alquiler(BI_ALQUILER_TIEMPO_ID, BI_ALQUILER_AMBIENTES_ID, BI_ALQUILER_UBICACION_ID, BI_ALQUILER_TIPO_OPERACION_ID, BI_ALQUILER_SUCURSAL_CODIGO, BI_ALQUILER_RANGO_M2_ID, BI_ALQUILER_TIPO_INMUEBLE_ID, BI_ALQUILER_RANGO_ETARIO_ID, BI_ALQUILER_PAGO_ID, BI_ALQUILER_ESTADO_ALQUILER_ID)
--	SELECT
--		(SELECT TIEMPO_ID 
--		from SQLSQUAD.BI_Tiempo
--		where TIEMPO_AÑO = year(a.ALQUILER_FECHA_INICIO) 
--		and TIEMPO_CUATRIMESTRE = DATEPART(QUARTER, a.ALQUILER_FECHA_INICIO)
--		and TIEMPO_MES = month(a.ALQUILER_FECHA_INICIO) AND TIEMPO_ID  IS NOT NULL),
--	I.INMUEBLE_CANT_AMBIENTES_ID,
--		(SELECT UBICACION_ID 
--		from SQLSQUAD.BI_Ubicacion
--		where UBICACION_BARRIO = b.BARRIO_NOMBRE
--		and UBICACION_LOCALIDAD = L.LOCALIDAD_NOMBRE
--		and UBICACION_PROVINICIA = p.PROVINCIA_NOMBRE),
--	An.ANUNCIO_TIPO_OPERACION_ID,
--	Ag.AGENTE_SUCURSAL_CODIGO,
--	SQLSQUAD.calcular_Rango_m2(I.INMUEBLE_SUPERFICIETOTAL),
--	I.INMUEBLE_TIPO_INMUEBLE_ID,
--	SQLSQUAD.calcular_Rango_etario(SQLSQUAD.calcularEdad(Ag.AGENTE_FECHA_NAC)),
--	pa.PAGO_ALQUILER_CODIGO,
--	A.ALQUILER_ESTADO_ALQUILER
--	from SQLSQUAD.alquiler a
--	JOIN SQLSQUAD.anuncio an on a.alquiler_ANUNCIO_CODIGO = an.ANUNCIO_CODIGO
--	join SQLSQUAD.inmueble I on an.ANUNCIO_INMUEBLE_CODIGO = I.INMUEBLE_CODIGO
--	join SQLSQUAD.agente Ag on An.ANUNCIO_AGENTE_CODIGO = Ag.AGENTE_CODIGO
--	join SQLSQUAD.direccion d on I.INMUEBLE_DIRECCION_ID = d.DIRECCION_ID
--	join SQLSQUAD.barrio b on d.DIRECCION_BARRIO_ID = b.BARRIO_ID
--	join SQLSQUAD.localidad l on b.BARRIO_LOCALIDAD_ID = l.LOCALIDAD_ID
--	join SQLSQUAD.provincia p on l.LOCALIDAD_PROVINCIA_ID = p.PROVINCIA_ID
--	join sqlsquad.pago_alquiler pa on pa.PAGO_ALQUILER_ALQUILER_CODIGO = a.ALQUILER_CODIGO
--	join SQLSQUAD.estado_alquiler ea on ea.ESTADO_ALQUILER_ID = A.ALQUILER_ESTADO_ALQUILER
--	--GROUP BY	year(a.ALQUILER_FECHA_INICIO), 
--	--			DATEPART(QUARTER, a.ALQUILER_FECHA_INICIO), 
--	--			month(a.ALQUILER_FECHA_INICIO), 
--	--			i.INMUEBLE_CANT_AMBIENTES_ID,
--	--			b.BARRIO_ID, b.BARRIO_NOMBRE,
--	--			l.LOCALIDAD_ID, l.LOCALIDAD_NOMBRE,
--	--			p.PROVINCIA_NOMBRE, p.PROVINCIA_NOMBRE,
--	--			an.ANUNCIO_TIPO_OPERACION_ID,
--	--			ag.AGENTE_SUCURSAL_CODIGO,
--	--			SQLSQUAD.calcular_Rango_m2(i.INMUEBLE_SUPERFICIETOTAL),
--	--			i.INMUEBLE_TIPO_INMUEBLE_ID,
--	--			SQLSQUAD.calcular_Rango_etario(SQLSQUAD.calcularEdad(Ag.AGENTE_FECHA_NAC)),
--	--			pa.PAGO_ALQUILER_CODIGO,
--	--			A.ALQUILER_ESTADO_ALQUILER
--END
--GO


ALTER PROCEDURE MigrarDatosBI_Alquiler
AS
BEGIN
	INSERT INTO SQLSQUAD.BI_Alquiler(BI_ALQUILER_TIEMPO_ID, BI_ALQUILER_UBICACION_ID, BI_ALQUILER_TIPO_OPERACION_ID, BI_ALQUILER_SUCURSAL_CODIGO, BI_ALQUILER_TIPO_INMUEBLE_ID, BI_ALQUILER_RANGO_ETARIO_ID, BI_ALQUILER_PAGO_ID, BI_ALQUILER_ESTADO_ALQUILER_ID, BI_ALQUILER_COMISION)
	SELECT BI_TIEMPO_ID, BI_UBICACION_ID, ANUNCIO_TIPO_OPERACION_ID, AGENTE_SUCURSAL_CODIGO, INMUEBLE_TIPO_INMUEBLE_ID, SQLSQUAD.calcular_Rango_etario(SQLSQUAD.calcularEdad(AGENTE_FECHA_NAC)), PAGO_ALQUILER_CODIGO, ALQUILER_ESTADO_ALQUILER, SUM(ALQUILER_COMISION)
	FROM SQLSQUAD.alquiler
	JOIN SQLSQUAD.anuncio		ON ALQUILER_ANUNCIO_CODIGO    = ANUNCIO_CODIGO
	JOIN SQLSQUAD.inmueble		ON ANUNCIO_INMUEBLE_CODIGO    = INMUEBLE_CODIGO
	JOIN SQLSQUAD.agente        ON ANUNCIO_AGENTE_CODIGO      = AGENTE_CODIGO
	JOIN SQLSQUAD.direccion		ON INMUEBLE_DIRECCION_ID      = DIRECCION_ID
	JOIN SQLSQUAD.barrio		ON DIRECCION_BARRIO_ID        = BARRIO_ID
	JOIN SQLSQUAD.localidad		ON BARRIO_LOCALIDAD_ID        = LOCALIDAD_ID
	JOIN SQLSQUAD.provincia		ON LOCALIDAD_PROVINCIA_ID     = PROVINCIA_ID
	JOIN SQLSQUAD.BI_Tiempo		ON (SELECT BI_TIEMPO_ID 
										FROM SQLSQUAD.BI_Tiempo
										WHERE BI_TIEMPO_AÑO            = YEAR(ALQUILER_FECHA_INICIO) 
											AND BI_TIEMPO_CUATRIMESTRE = DATEPART(QUARTER, ALQUILER_FECHA_INICIO)
											AND BI_TIEMPO_MES          = MONTH(ALQUILER_FECHA_INICIO))           = BI_TIEMPO_ID
	JOIN SQLSQUAD.BI_Ubicacion  ON (SELECT BI_UBICACION_ID 
										FROM SQLSQUAD.BI_Ubicacion
										WHERE BARRIO_NOMBRE	= BI_UBICACION_BARRIO
											AND LOCALIDAD_NOMBRE	  = BI_UBICACION_LOCALIDAD
											AND PROVINCIA_NOMBRE	  = BI_UBICACION_PROVINCIA)					 = BI_UBICACION_ID

	JOIN SQLSQUAD.pago_alquiler ON PAGO_ALQUILER_ALQUILER_CODIGO = ALQUILER_CODIGO
	GROUP BY BI_TIEMPO_ID, BI_UBICACION_ID, ANUNCIO_TIPO_OPERACION_ID, AGENTE_SUCURSAL_CODIGO, INMUEBLE_TIPO_INMUEBLE_ID, SQLSQUAD.calcular_Rango_etario(SQLSQUAD.calcularEdad(AGENTE_FECHA_NAC)), PAGO_ALQUILER_CODIGO, ALQUILER_ESTADO_ALQUILER
END
GO

ALTER PROCEDURE MigrarDatosBI_Venta
AS
BEGIN
	INSERT INTO SQLSQUAD.BI_Venta_inmueble(BI_VENTA_TIEMPO_ID, BI_VENTA_UBICACION_ID, BI_VENTA_TIPO_OPERACION_ID, BI_VENTA_SUCURSAL_CODIGO, BI_VENTA_TIPO_MONEDA_ID, BI_VENTA_RANGO_M2_ID, BI_VENTA_TIPO_INMUEBLE_ID,BI_VENTA_PRECIO, BI_VENTA_COMISION)
	SELECT BI_TIEMPO_ID, BI_UBICACION_ID, ANUNCIO_TIPO_OPERACION_ID, AGENTE_SUCURSAL_CODIGO, VENTA_MONEDA_ID, SQLSQUAD.calcular_Rango_m2(INMUEBLE_SUPERFICIETOTAL), INMUEBLE_TIPO_INMUEBLE_ID, SUM(VENTA_PRECIO_VENTA), SUM(VENTA_COMISION)
	FROM SQLSQUAD.venta
	JOIN SQLSQUAD.anuncio		ON VENTA_ANUNCIO_CODIGO       = ANUNCIO_CODIGO
	JOIN SQLSQUAD.inmueble		ON ANUNCIO_INMUEBLE_CODIGO    = INMUEBLE_CODIGO
	JOIN SQLSQUAD.agente        ON ANUNCIO_AGENTE_CODIGO      = AGENTE_CODIGO
	JOIN SQLSQUAD.direccion		ON INMUEBLE_DIRECCION_ID      = DIRECCION_ID
	JOIN SQLSQUAD.barrio		ON DIRECCION_BARRIO_ID        = BARRIO_ID
	JOIN SQLSQUAD.localidad		ON BARRIO_LOCALIDAD_ID        = LOCALIDAD_ID
	JOIN SQLSQUAD.provincia		ON LOCALIDAD_PROVINCIA_ID     = PROVINCIA_ID
	JOIN SQLSQUAD.BI_Tiempo		ON (SELECT BI_TIEMPO_ID 
									FROM SQLSQUAD.BI_Tiempo

									WHERE BI_TIEMPO_AÑO            = YEAR(VENTA_FECHA) 
										AND BI_TIEMPO_CUATRIMESTRE = DATEPART(QUARTER, VENTA_FECHA)
										AND BI_TIEMPO_MES          = MONTH(VENTA_FECHA))           = BI_TIEMPO_ID
	JOIN SQLSQUAD.BI_Ubicacion  ON (SELECT BI_UBICACION_ID 
									FROM SQLSQUAD.BI_Ubicacion
									WHERE BARRIO_NOMBRE	= BI_UBICACION_BARRIO
										AND LOCALIDAD_NOMBRE	  = BI_UBICACION_LOCALIDAD
										AND PROVINCIA_NOMBRE	  = BI_UBICACION_PROVINCIA)		   = BI_UBICACION_ID
	GROUP BY BI_TIEMPO_ID, BI_UBICACION_ID, ANUNCIO_TIPO_OPERACION_ID, AGENTE_SUCURSAL_CODIGO, VENTA_MONEDA_ID, SQLSQUAD.calcular_Rango_m2(INMUEBLE_SUPERFICIETOTAL), INMUEBLE_TIPO_INMUEBLE_ID
END
GO


--ALTER PROCEDURE MigrarDatosBI_Venta
--AS
--BEGIN
--	INSERT INTO SQLSQUAD.BI_Venta_inmueble(BI_VENTA_TIEMPO_ID, BI_VENTA_UBICACION_ID, BI_VENTA_TIPO_OPERACION_ID, BI_VENTA_SUCURSAL_CODIGO, BI_VENTA_TIPO_MONEDA_ID, BI_VENTA_RANGO_M2_ID, BI_VENTA_TIPO_INMUEBLE_ID,BI_VENTA_PRECIO, BI_VENTA_COMISION)
--	SELECT
--		(SELECT TIEMPO_ID 
--		from SQLSQUAD.BI_Tiempo
--		where TIEMPO_AÑO = year(V.VENTA_FECHA) 
--		and TIEMPO_CUATRIMESTRE = DATEPART(QUARTER, V.VENTA_FECHA)
--		and TIEMPO_MES = month(V.VENTA_FECHA)),
--	I.INMUEBLE_CANT_AMBIENTES_ID,
--		(SELECT UBICACION_ID 
--		from SQLSQUAD.BI_Ubicacion
--		where UBICACION_BARRIO = b.BARRIO_NOMBRE
--		and UBICACION_LOCALIDAD = L.LOCALIDAD_NOMBRE
--		and UBICACION_PROVINICIA = p.PROVINCIA_NOMBRE),
--	An.ANUNCIO_TIPO_OPERACION_ID,
--	Ag.AGENTE_SUCURSAL_CODIGO,
--	v.VENTA_MONEDA_ID,
--	SQLSQUAD.calcular_Rango_m2(I.INMUEBLE_SUPERFICIETOTAL),
--	I.INMUEBLE_TIPO_INMUEBLE_ID
--	from SQLSQUAD.venta v
--	JOIN SQLSQUAD.anuncio an on v.VENTA_ANUNCIO_CODIGO = an.ANUNCIO_CODIGO
--	join SQLSQUAD.inmueble I on an.ANUNCIO_INMUEBLE_CODIGO = I.INMUEBLE_CODIGO
--	join SQLSQUAD.agente Ag on An.ANUNCIO_AGENTE_CODIGO = Ag.AGENTE_CODIGO
--	join SQLSQUAD.direccion d on I.INMUEBLE_DIRECCION_ID = d.DIRECCION_ID
--	join SQLSQUAD.barrio b on d.DIRECCION_BARRIO_ID = b.BARRIO_ID
--	join SQLSQUAD.localidad l on b.BARRIO_LOCALIDAD_ID = l.LOCALIDAD_ID
--	join SQLSQUAD.provincia p on l.LOCALIDAD_PROVINCIA_ID = p.PROVINCIA_ID
----	GROUP BY	year(V.VENTA_FECHA), 
----				DATEPART(QUARTER, V.VENTA_FECHA), 
----				month(V.VENTA_FECHA), 
----				i.INMUEBLE_CANT_AMBIENTES_ID,
----				b.BARRIO_ID, b.BARRIO_NOMBRE,
----				l.LOCALIDAD_ID, l.LOCALIDAD_NOMBRE,
----				p.PROVINCIA_NOMBRE, p.PROVINCIA_NOMBRE,
----				an.ANUNCIO_TIPO_OPERACION_ID,
----				ag.AGENTE_SUCURSAL_CODIGO,
----				v.VENTA_MONEDA_ID,
----				SQLSQUAD.calcular_Rango_m2(I.INMUEBLE_SUPERFICIETOTAL),
----				i.INMUEBLE_TIPO_INMUEBLE_ID
--END

------------------ TRANSACCION ---------------------------
GO
BEGIN TRANSACTION
				   EXEC MigrarDatosBI_Rango_Etario
				   EXEC MigrarDatosBI_Ambientes
				   EXEC MigrarDatosBI_Pago
				   EXEC MigrarDatosBI_Rango_m2
				   EXEC MigrarDatosBI_Sucursal
				   EXEC MigrarDatosBI_Tiempo
				   EXEC MigrarDatosBI_Tipo_Inmueble
				   EXEC MigrarDatosBI_Tipo_Moneda
				   EXEC MigrarDatosBI_Tipo_Operacion
				   EXEC MigrarDatosBI_Ubicacion
				   EXEC MigrarDatosBI_Estado_Alquiler
				   EXEC MigrarDatosBI_Estado_Anuncio
				   EXEC MigrarDatosBI_Anuncio
				   EXEC MigrarDatosBI_Alquiler
				   EXEC MigrarDatosBI_Venta

COMMIT TRANSACTION
GO

--1. Duración promedio (en días) que se encuentran publicados los anuncios
--según el tipo de operación (alquiler, venta, etc), barrio y ambientes para cada
--cuatrimestre de cada año. Se consideran todos los anuncios que se dieron de alta
--en ese cuatrimestre. La duración se calcula teniendo en cuenta la fecha de alta y
--la fecha de finalización.


CREATE VIEW SQLSQUAD.BI_duracion_promedio
AS
SELECT BI_TIEMPO_AÑO, BI_TIEMPO_CUATRIMESTRE, BI_TIPO_OPERACION_NOMBRE, BI_UBICACION_BARRIO, BI_AMBIENTES_NOMBRE, AVG(BI_ANUNCIO_DURACION) AS [Duracion promedio en días publicados] FROM SQLSQUAD.BI_Anuncio
JOIN SQLSQUAD.BI_Tiempo ON BI_TIEMPO_ID					= BI_ANUNCIO_TIEMPO_ID
JOIN SQLSQUAD.BI_Tipo_Operacion ON BI_TIPO_OPERACION_ID = BI_ANUNCIO_TIPO_OPERACION_ID
JOIN SQLSQUAD.BI_Ubicacion ON BI_UBICACION_ID			= BI_ANUNCIO_UBICACION_ID
JOIN SQLSQUAD.BI_Ambientes ON BI_AMBIENTES_ID			= BI_ANUNCIO_AMBIENTES_ID
GROUP BY BI_TIEMPO_AÑO, BI_TIEMPO_CUATRIMESTRE, BI_TIPO_OPERACION_NOMBRE, BI_UBICACION_BARRIO, BI_AMBIENTES_NOMBRE

--2. Precio promedio de los anuncios de inmuebles según el tipo de operación
--(alquiler, venta, etc), tipo de inmueble y rango m2 para cada cuatrimestre/año.
--Se consideran todos los anuncios que se dieron de alta en ese cuatrimestre. El
--precio se debe expresar en el tipo de moneda que corresponda, identificando de
--cuál se trata.

CREATE VIEW SQLSQUAD.BI_precio_promedio
AS
SELECT BI_TIEMPO_AÑO, BI_TIEMPO_CUATRIMESTRE, BI_TIPO_OPERACION_NOMBRE, BI_TIPO_INMUEBLE_NOMBRE, MAYOR_A_100, ENTRE_75_Y_100, ENTRE_55_75, ENTRE_35_Y_55, MENOR_A_35 , SQLSQUAD.SignoMoneda(BI_TIPO_MONEDA_NOMBRE) + ' '+ CAST(AVG(BI_ANUNCIO_COSTO) AS NVARCHAR(100)), BI_TIPO_MONEDA_NOMBRE FROM SQLSQUAD.BI_Anuncio
JOIN SQLSQUAD.BI_Tipo_Operacion ON BI_TIPO_OPERACION_ID = BI_ANUNCIO_TIPO_OPERACION_ID
JOIN SQLSQUAD.BI_Tipo_Inmueble ON BI_TIPO_INMUEBLE_ID = BI_ANUNCIO_TIPO_INMUEBLE_ID
JOIN SQLSQUAD.BI_Rango_m2 ON RANGO_M2_ID = BI_ANUNCIO_RANGO_M2_ID
JOIN SQLSQUAD.BI_Tiempo ON BI_TIEMPO_ID = BI_ANUNCIO_TIEMPO_ID
JOIN SQLSQUAD.BI_Tipo_moneda ON BI_TIPO_MONEDA_ID = BI_ANUNCIO_TIPO_MONEDA_ID
GROUP BY BI_TIEMPO_AÑO, BI_TIEMPO_CUATRIMESTRE, BI_TIPO_OPERACION_NOMBRE, BI_TIPO_INMUEBLE_NOMBRE, MAYOR_A_100, ENTRE_75_Y_100, ENTRE_55_75, ENTRE_35_Y_55, MENOR_A_35, BI_TIPO_MONEDA_NOMBRE


--3. Los 5 barrios más elegidos para alquilar en función del rango etario de los
--inquilinos para cada cuatrimestre/año. Se calcula en función de los alquileres
--dados de alta en dicho periodo.

CREATE VIEW SQLSQUAD.BI_barrios_mas_elegidos
AS
SELECT DISTINCT TOP 5 BI_TIEMPO_AÑO, BI_TIEMPO_CUATRIMESTRE, BI_UBICACION_BARRIO, MENOR_A_25, MAYOR_A_50, ENTRE_25_Y_35, ENTRE_35_Y_50, COUNT(*) 
FROM SQLSQUAD.BI_Alquiler
JOIN SQLSQUAD.BI_Ubicacion	  ON BI_UBICACION_ID             = BI_ALQUILER_UBICACION_ID
JOIN SQLSQUAD.BI_Tiempo		  ON BI_TIEMPO_ID                = BI_ALQUILER_TIEMPO_ID
JOIN SQLSQUAD.BI_Rango_Etario ON BI_ALQUILER_RANGO_ETARIO_ID = RANGO_ETARIO_ID
GROUP BY BI_TIEMPO_AÑO, BI_TIEMPO_CUATRIMESTRE, BI_UBICACION_BARRIO, MENOR_A_25, MAYOR_A_50, ENTRE_25_Y_35, ENTRE_35_Y_50
ORDER BY COUNT(*) DESC	


SELECT DISTINCT BI_TIEMPO_AÑO, BI_TIEMPO_CUATRIMESTRE, BI_UBICACION_BARRIO, (SELECT CASE WHEN MENOR_A_25 = 1 THEN 'MENOR A 25'
																						 WHEN MAYOR_A_50 = 1 THEN 'MAYOR A 50'
																						 WHEN ENTRE_25_Y_35 = 1 THEN 'ENTRE 25 Y 35'
																						 WHEN ENTRE_35_Y_50 = 1 THEN 'ENTRE 35 Y 50'
																						 END) AS [Rango Etario], COUNT(*) AS [Cantidad de barrios elegidos]
FROM SQLSQUAD.BI_Anuncio
JOIN SQLSQUAD.BI_Ubicacion	  ON BI_UBICACION_ID             = BI_ANUNCIO_UBICACION_ID
JOIN SQLSQUAD.BI_Tiempo		  ON BI_TIEMPO_ID                = BI_ANUNCIO_TIEMPO_ID
JOIN SQLSQUAD.BI_Rango_Etario ON BI_ANUNCIO_RANGO_ETARIO_ID  = RANGO_ETARIO_ID
GROUP BY BI_TIEMPO_AÑO, BI_TIEMPO_CUATRIMESTRE, BI_UBICACION_BARRIO, MENOR_A_25, MAYOR_A_50, ENTRE_25_Y_35, ENTRE_35_Y_50
ORDER BY COUNT(*) DESC	
GO

SELECT BI_TIEMPO_AÑO, BI_TIEMPO_CUATRIMESTRE, BI_UBICACION_BARRIO, [Rango Etario], [Cantidad de Barrios Elegidos]
FROM (
    SELECT BI_TIEMPO_AÑO, BI_TIEMPO_CUATRIMESTRE, BI_UBICACION_BARRIO, CASE WHEN MENOR_A_25    = 1 THEN 'MENOR A 25' 
																			WHEN MAYOR_A_50    = 1 THEN 'MAYOR A 50'
																			WHEN ENTRE_25_Y_35 = 1 THEN 'ENTRE 25 Y 35'
																			WHEN ENTRE_35_Y_50 = 1 THEN 'ENTRE 35 Y 50'
																			END AS [Rango Etario],
																	   COUNT(*) AS [Cantidad de Barrios Elegidos],
																	   ROW_NUMBER() OVER (PARTITION BY BI_TIEMPO_AÑO, BI_TIEMPO_CUATRIMESTRE
																							ORDER BY COUNT(*) DESC) AS NumeroFila
    FROM SQLSQUAD.BI_Anuncio
    JOIN SQLSQUAD.BI_Ubicacion	  ON BI_UBICACION_ID            = BI_ANUNCIO_UBICACION_ID
    JOIN SQLSQUAD.BI_Tiempo		  ON BI_TIEMPO_ID               = BI_ANUNCIO_TIEMPO_ID
    JOIN SQLSQUAD.BI_Rango_Etario ON BI_ANUNCIO_RANGO_ETARIO_ID = RANGO_ETARIO_ID
    GROUP BY BI_TIEMPO_AÑO, BI_TIEMPO_CUATRIMESTRE, BI_UBICACION_BARRIO, MENOR_A_25, MAYOR_A_50, ENTRE_25_Y_35, ENTRE_35_Y_50
) AS S
WHERE NumeroFila <= 5
ORDER BY BI_TIEMPO_AÑO, BI_TIEMPO_CUATRIMESTRE, [Rango Etario], NumeroFila

--4. Porcentaje de incumplimiento de pagos de alquileres en término por cada
--mes/año. Se calcula en función de las fechas de pago y fecha de vencimiento del
--mismo. El porcentaje es en función del total de pagos en dicho periodo.

CREATE VIEW SQLSQUAD.BI_incumplimiento_pagos
AS
SELECT BI_TIEMPO_AÑO, BI_TIEMPO_MES, SUM(SQLSQUAD.noCumplioPago(BI_PAGO_FECHA, BI_PAGO_FECHA_VENCIMIENTO))/COUNT(*)*100 FROM SQLSQUAD.BI_Alquiler
JOIN SQLSQUAD.BI_Pago ON BI_PAGO_ID = BI_ALQUILER_PAGO_ID
JOIN SQLSQUAD.BI_Tiempo ON BI_TIEMPO_ID = BI_ALQUILER_TIEMPO_ID
GROUP BY BI_TIEMPO_AÑO, BI_TIEMPO_MES

--5. Porcentaje promedio de incremento del valor de los alquileres para los
--contratos en curso por mes/año. Se calcula tomando en cuenta el último pago
--con respecto al del mes en curso, únicamente de aquellos alquileres que hayan
--tenido aumento y están activos.

CREATE VIEW SQLSQUAD.BI_incremento
AS
SELECT BI_TIEMPO_AÑO, BI_TIEMPO_MES, AVG(BI_PAGO_IMPORTE*100/
								  (SELECT BI_PAGO_IMPORTE FROM SQLSQUAD.BI_Pago
									JOIN SQLSQUAD.BI_Alquiler ON BI_PAGO_ID = BI_ALQUILER_PAGO_ID
									WHERE BI_TIEMPO_MES = MONTH(GETDATE()) 
									AND BI_TIEMPO_AÑO = YEAR(GETDATE()))) 
FROM SQLSQUAD.BI_Alquiler
JOIN SQLSQUAD.BI_Pago ON BI_PAGO_ID = BI_ALQUILER_PAGO_ID
JOIN SQLSQUAD.BI_Tiempo ON BI_TIEMPO_ID = BI_ALQUILER_TIEMPO_ID
JOIN SQLSQUAD.BI_Estado_Alquiler ON BI_ESTADO_ALQUILER_ID = BI_ALQUILER_ESTADO_ALQUILER_ID
WHERE BI_PAGO_IMPORTE < (SELECT BI_PAGO_IMPORTE FROM SQLSQUAD.BI_Pago
					  JOIN SQLSQUAD.BI_Alquiler ON BI_PAGO_ID = BI_ALQUILER_PAGO_ID
						WHERE BI_TIEMPO_MES = MONTH(GETDATE()) AND BI_TIEMPO_AÑO = YEAR(GETDATE()))
	  AND BI_ESTADO_ALQUILER_NOMBRE = 'Activo'
GROUP BY BI_TIEMPO_AÑO, BI_TIEMPO_MES

--6. Precio promedio de m2 de la venta de inmuebles según el tipo de inmueble y
--la localidad para cada cuatrimestre/año. Se calcula en función de las ventas
--concretadas.

CREATE VIEW SQLSQUAD.BI_precio_prom_m2
AS
SELECT BI_TIEMPO_AÑO, BI_TIEMPO_CUATRIMESTRE, BI_TIPO_INMUEBLE_NOMBRE, BI_UBICACION_LOCALIDAD, AVG(BI_VENTA_PRECIO)
FROM SQLSQUAD.BI_Venta_inmueble
JOIN SQLSQUAD.BI_Tipo_inmueble ON BI_TIPO_INMUEBLE_ID = BI_VENTA_TIPO_INMUEBLE_ID
JOIN SQLSQUAD.BI_Ubicacion	   ON BI_UBICACION_ID     = BI_VENTA_UBICACION_ID 
JOIN SQLSQUAD.BI_Tiempo        ON BI_TIEMPO_ID        = BI_VENTA_TIEMPO_ID
GROUP BY BI_TIEMPO_AÑO, BI_TIEMPO_CUATRIMESTRE, BI_TIPO_INMUEBLE_NOMBRE, BI_UBICACION_LOCALIDAD
GO

-- V2
CREATE VIEW SQLSQUAD.BI_precio_prom_m2
AS
SELECT BI_TIEMPO_AÑO, BI_TIEMPO_CUATRIMESTRE, BI_TIPO_INMUEBLE_NOMBRE, BI_UBICACION_LOCALIDAD, AVG(BI_VENTA_PRECIO/BI_VENTA_SUPERFICIETOTAL)
FROM SQLSQUAD.BI_Venta_inmueble
JOIN SQLSQUAD.BI_Tipo_inmueble ON BI_TIPO_INMUEBLE_ID = BI_VENTA_TIPO_INMUEBLE_ID
JOIN SQLSQUAD.BI_Ubicacion	   ON BI_UBICACION_ID     = BI_VENTA_UBICACION_ID 
JOIN SQLSQUAD.BI_Tiempo        ON BI_TIEMPO_ID        = BI_VENTA_TIEMPO_ID
GROUP BY BI_TIEMPO_AÑO, BI_TIEMPO_CUATRIMESTRE, BI_TIPO_INMUEBLE_NOMBRE, BI_UBICACION_LOCALIDAD, BI_VENTA_PRECIO
GO

--7. Valor promedio de la comisión según el tipo de operación (alquiler, venta, etc)
--y sucursal para cada cuatrimestre/año. Se calcula en función de los alquileres y
--ventas concretadas dentro del periodo.
CREATE VIEW SQLSQUAD.BI_valor_prom_comision
AS
SELECT BI_TIEMPO_AÑO, BI_TIEMPO_CUATRIMESTRE, BI_TIPO_OPERACION_NOMBRE, BI_SUCURSAL_CODIGO, AVG(BI_VENTA_COMISION) AS [Promedio de comisión]
FROM SQLSQUAD.BI_Venta_inmueble
JOIN SQLSQUAD.BI_Sucursal		ON BI_SUCURSAL_CODIGO		  = BI_VENTA_SUCURSAL_CODIGO
JOIN SQLSQUAD.BI_Tiempo			ON BI_TIEMPO_ID				  = BI_VENTA_TIEMPO_ID
JOIN SQLSQUAD.BI_Tipo_operacion ON BI_VENTA_TIPO_OPERACION_ID = BI_TIPO_OPERACION_ID
GROUP BY BI_TIEMPO_AÑO, BI_TIEMPO_CUATRIMESTRE, BI_TIPO_OPERACION_NOMBRE, BI_SUCURSAL_CODIGO
UNION
SELECT BI_TIEMPO_AÑO, BI_TIEMPO_CUATRIMESTRE, BI_TIPO_OPERACION_NOMBRE, BI_SUCURSAL_CODIGO, AVG(BI_ALQUILER_COMISION) AS [Promedio de comisión]
FROM SQLSQUAD.BI_Alquiler
JOIN SQLSQUAD.BI_Sucursal		ON BI_SUCURSAL_CODIGO		  = BI_ALQUILER_SUCURSAL_CODIGO
JOIN SQLSQUAD.BI_Tiempo			ON BI_TIEMPO_ID				  = BI_ALQUILER_TIEMPO_ID
JOIN SQLSQUAD.BI_Tipo_operacion ON BI_ALQUILER_TIPO_OPERACION_ID = BI_TIPO_OPERACION_ID
GROUP BY BI_TIEMPO_AÑO, BI_TIEMPO_CUATRIMESTRE, BI_TIPO_OPERACION_NOMBRE, BI_SUCURSAL_CODIGO
GO

--8. Porcentaje de operaciones concretadas (tanto de alquileres como ventas) por
--cada sucursal, según el rango etario de los empleados por año en función de la
--cantidad de anuncios publicados en ese mismo año.
CREATE VIEW SQLSQUAD.BI_valor_porcentaje_operaciones_concretadas
AS
SELECT T1.BI_TIEMPO_AÑO, BI_SUCURSAL_CODIGO, (SELECT CASE WHEN RANGO_ETARIO_ID = 1 THEN 'MAYOR A 50'
													   WHEN RANGO_ETARIO_ID = 2 THEN 'ENTRE 35 Y 50'
													   WHEN RANGO_ETARIO_ID = 3 THEN 'ENTRE 25 Y 35'
													   WHEN RANGO_ETARIO_ID = 4 THEN 'MENOR A 25'
													   END) AS [Rango Etario]
											, (SELECT COUNT(*) 
												FROM SQLSQUAD.BI_Anuncio A2
												JOIN SQLSQUAD.BI_Tiempo T2 ON BI_ANUNCIO_TIEMPO_ID = BI_TIEMPO_ID
												JOIN SQLSQUAD.BI_Rango_Etario ON RANGO_ETARIO_ID   = A1.BI_ANUNCIO_RANGO_ETARIO_ID
												WHERE (A2.BI_ANUNCIO_ESTADO_ANUNCIO_ID = 1 OR A2.BI_ANUNCIO_ESTADO_ANUNCIO_ID = 3)
												AND A2.BI_ANUNCIO_SUCURSAL_CODIGO = BI_SUCURSAL_CODIGO
												AND T2.BI_TIEMPO_AÑO = T1.BI_TIEMPO_AÑO)* 100 / COUNT(*)
FROM SQLSQUAD.BI_Anuncio A1
JOIN SQLSQUAD.BI_Sucursal	  ON BI_SUCURSAL_CODIGO = A1.BI_ANUNCIO_SUCURSAL_CODIGO
JOIN SQLSQUAD.BI_Tiempo	 T1	  ON BI_TIEMPO_ID       = A1.BI_ANUNCIO_TIEMPO_ID
JOIN SQLSQUAD.BI_Rango_Etario ON RANGO_ETARIO_ID    = A1.BI_ANUNCIO_RANGO_ETARIO_ID
GROUP BY BI_TIEMPO_AÑO, BI_SUCURSAL_CODIGO, RANGO_ETARIO_ID

-- VERSION 2
SELECT T1.BI_TIEMPO_AÑO, BI_SUCURSAL_CODIGO, (SELECT CASE WHEN RANGO_ETARIO_ID = 1 THEN 'MAYOR A 50'
													   WHEN RANGO_ETARIO_ID = 2 THEN 'ENTRE 35 Y 50'
													   WHEN RANGO_ETARIO_ID = 3 THEN 'ENTRE 25 Y 35'
													   WHEN RANGO_ETARIO_ID = 4 THEN 'MENOR A 25'
													   END) AS [Rango Etario]
										   , (SELECT COUNT(*)
												FROM SQLSQUAD.BI_Anuncio A2
												JOIN SQLSQUAD.BI_Sucursal	  ON BI_SUCURSAL_CODIGO = A2.BI_ANUNCIO_SUCURSAL_CODIGO
												JOIN SQLSQUAD.BI_Tiempo	 T2	  ON BI_TIEMPO_ID       = A2.BI_ANUNCIO_TIEMPO_ID
												JOIN SQLSQUAD.BI_Rango_Etario ON RANGO_ETARIO_ID    = A2.BI_ANUNCIO_RANGO_ETARIO_ID
												WHERE (BI_ANUNCIO_ESTADO_ANUNCIO_ID = 1 OR BI_ANUNCIO_ESTADO_ANUNCIO_ID = 3)
												AND A2.BI_ANUNCIO_SUCURSAL_CODIGO = BI_SUCURSAL_CODIGO AND T2.BI_TIEMPO_AÑO = T1.BI_TIEMPO_AÑO AND A2.BI_ANUNCIO_RANGO_ETARIO_ID = R1.RANGO_ETARIO_ID
												)*100 / COUNT(*) AS [Porcentaje de operaciones concretadas]
FROM SQLSQUAD.BI_Anuncio A1
JOIN SQLSQUAD.BI_Sucursal	  ON BI_SUCURSAL_CODIGO = A1.BI_ANUNCIO_SUCURSAL_CODIGO
JOIN SQLSQUAD.BI_Tiempo	T1	  ON BI_TIEMPO_ID       = A1.BI_ANUNCIO_TIEMPO_ID
JOIN SQLSQUAD.BI_Rango_Etario R1 ON RANGO_ETARIO_ID    = A1.BI_ANUNCIO_RANGO_ETARIO_ID
GROUP BY BI_TIEMPO_AÑO, BI_SUCURSAL_CODIGO, RANGO_ETARIO_ID

--9. Monto total de cierre de contratos por tipo de operación (tanto de alquileres
--como ventas) por cada cuatrimestre y sucursal, diferenciando el tipo de moneda

CREATE VIEW SQLSQUAD.BI_monto_total_cierre_contratos
AS
SELECT BI_TIEMPO_AÑO, BI_TIEMPO_CUATRIMESTRE, BI_TIPO_OPERACION_NOMBRE, BI_SUCURSAL_CODIGO, SUM(BI_VENTA_PRECIO)
FROM SQLSQUAD.BI_Venta_inmueble
JOIN SQLSQUAD.BI_Sucursal		ON BI_SUCURSAL_CODIGO		  = BI_VENTA_SUCURSAL_CODIGO
JOIN SQLSQUAD.BI_Tiempo 		ON BI_TIEMPO_ID				  = BI_VENTA_TIEMPO_ID
JOIN SQLSQUAD.BI_Tipo_operacion ON BI_VENTA_TIPO_OPERACION_ID = BI_TIPO_OPERACION_ID
GROUP BY BI_TIEMPO_AÑO, BI_TIEMPO_CUATRIMESTRE, BI_TIPO_OPERACION_NOMBRE, BI_SUCURSAL_CODIGO
UNION
SELECT BI_TIEMPO_AÑO, BI_TIEMPO_CUATRIMESTRE, BI_TIPO_OPERACION_NOMBRE, BI_SUCURSAL_CODIGO, SUM(BI_PAGO_IMPORTE)
FROM SQLSQUAD.BI_Alquiler
JOIN SQLSQUAD.BI_Sucursal		ON BI_SUCURSAL_CODIGO			 = BI_ALQUILER_SUCURSAL_CODIGO
JOIN SQLSQUAD.BI_Tiempo			ON BI_TIEMPO_ID					 = BI_ALQUILER_TIEMPO_ID
JOIN SQLSQUAD.BI_Tipo_operacion ON BI_ALQUILER_TIPO_OPERACION_ID = BI_TIPO_OPERACION_ID
JOIN SQLSQUAD.BI_Pago			ON BI_PAGO_ID = BI_ALQUILER_PAGO_ID
GROUP BY BI_TIEMPO_AÑO, BI_TIEMPO_CUATRIMESTRE, BI_TIPO_OPERACION_NOMBRE, BI_SUCURSAL_CODIGO

-- VERSION 2

SELECT BI_TIEMPO_AÑO, BI_TIEMPO_CUATRIMESTRE, BI_TIPO_OPERACION_NOMBRE, BI_SUCURSAL_CODIGO, SUM(BI_ANUNCIO_COSTO)
FROM SQLSQUAD.BI_Anuncio
JOIN SQLSQUAD.BI_Sucursal		ON BI_SUCURSAL_CODIGO		    = BI_ANUNCIO_SUCURSAL_CODIGO
JOIN SQLSQUAD.BI_Tiempo 		ON BI_TIEMPO_ID				    = BI_ANUNCIO_TIEMPO_ID
JOIN SQLSQUAD.BI_Tipo_operacion ON BI_ANUNCIO_TIPO_OPERACION_ID = BI_TIPO_OPERACION_ID
GROUP BY BI_TIEMPO_AÑO, BI_TIEMPO_CUATRIMESTRE, BI_TIPO_OPERACION_NOMBRE, BI_SUCURSAL_CODIGO







