--inmueble
CREATE PROCEDURE SQLSQUAD.MigrarDatosInmueble
AS
BEGIN
    INSERT INTO SQLSQUAD.inmueble (INMUEBLE_CODIGO, INMUEBLE_NOMBRE, INMUEBLE_EXPESAS, INMUEBLE_ANTIGUEDAD, INMUEBLE_DESCRIPCION, INMUEBLE_SUPERFICIETOTAL, INMUEBLE_TIPO_INMUEBLE_ID, INMUEBLE_DISPOSICION_ID, INMUEBLE_ORIENTACION_ID, INMUEBLE_CANT_AMBIENTES_ID, INMUEBLE_ESTADO_INMUEBLE_ID, INMUEBLE_DIRECCION_ID)
    SELECT DISTINCT
        M.INMUEBLE_CODIGO,
        M.INMUEBLE_NOMBRE,
        M.INMUEBLE_EXPESAS,
        M.INMUEBLE_ANTIGUEDAD,
        M.INMUEBLE_DESCRIPCION,
        M.INMUEBLE_SUPERFICIETOTAL,
        TI.TIPO_INMUEBLE_ID,
        DI.DISPOSICION_ID,
        ORI.ORIENTACION_ID,
        CA.CANT_AMBIENTES_ID,
        EI.ESTADO_INMUEBLE_ID,
        DIR.DIRECCION_ID
    FROM gd_esquema.Maestra AS M
    JOIN SQLSQUAD.tipo_inmueble AS TI ON TI.TIPO_INMUEBLE_NOMBRE = M.INMUEBLE_TIPO_INMUEBLE
    JOIN SQLSQUAD.disposicion AS DI ON DI.DISPOSICION_NOMBRE = M.INMUEBLE_DISPOSICION
    JOIN SQLSQUAD.orientacion AS ORI ON ORI.ORIENTACION_NOMBRE = M.INMUEBLE_ORIENTACION
    JOIN SQLSQUAD.cant_ambientes AS CA ON CA.CANT_AMBIENTES_NOMBRE = M.INMUEBLE_CANT_AMBIENTES
    JOIN SQLSQUAD.estado_inmueble AS EI ON EI.ESTADO_INMUEBLE_NOMBRE = M.INMUEBLE_ESTADO
    JOIN SQLSQUAD.direccion AS DIR ON SQLSQUAD.DireccionCompleta(DIR.DIRECCION_CALLE, DIR.DIRECCION_NUMERO_CALLE) = M.INMUEBLE_DIRECCION
	ORDER BY INMUEBLE_CODIGO
END
GO

--DATOS INMUEBLES
EXEC SQLSQUAD.MigrarDatosInmueble
GO

--inmueble_propietario
--caracteristica_inmueble

INSERT INTO SQLSQUAD.inmueble (INMUEBLE_CODIGO, INMUEBLE_NOMBRE, INMUEBLE_EXPESAS, INMUEBLE_ANTIGUEDAD, INMUEBLE_DESCRIPCION, INMUEBLE_SUPERFICIETOTAL, INMUEBLE_TIPO_INMUEBLE_ID, INMUEBLE_DISPOSICION_ID, INMUEBLE_ORIENTACION_ID, INMUEBLE_CANT_AMBIENTES_ID, INMUEBLE_ESTADO_INMUEBLE_ID, INMUEBLE_DIRECCION_ID)
    SELECT DISTINCT
        M.INMUEBLE_CODIGO,
        M.INMUEBLE_NOMBRE,
        M.INMUEBLE_EXPESAS,
        M.INMUEBLE_ANTIGUEDAD,
        M.INMUEBLE_DESCRIPCION,
        M.INMUEBLE_SUPERFICIETOTAL,
        TI.TIPO_INMUEBLE_ID,
        DI.DISPOSICION_ID,
        ORI.ORIENTACION_ID,
        CA.CANT_AMBIENTES_ID,
        EI.ESTADO_INMUEBLE_ID,
        DIR.DIRECCION_ID
    FROM gd_esquema.Maestra AS M
    JOIN SQLSQUAD.tipo_inmueble AS TI ON TI.TIPO_INMUEBLE_NOMBRE = M.INMUEBLE_TIPO_INMUEBLE
    JOIN SQLSQUAD.disposicion AS DI ON DI.DISPOSICION_NOMBRE = M.INMUEBLE_DISPOSICION
    JOIN SQLSQUAD.orientacion AS ORI ON ORI.ORIENTACION_NOMBRE = M.INMUEBLE_ORIENTACION
    JOIN SQLSQUAD.cant_ambientes AS CA ON CA.CANT_AMBIENTES_NOMBRE = M.INMUEBLE_CANT_AMBIENTES
    JOIN SQLSQUAD.estado_inmueble AS EI ON EI.ESTADO_INMUEBLE_NOMBRE = M.INMUEBLE_ESTADO
    JOIN SQLSQUAD.direccion AS DIR ON SQLSQUAD.DireccionCompleta(DIR.DIRECCION_CALLE, DIR.DIRECCION_NUMERO_CALLE) = M.INMUEBLE_DIRECCION
	JOIN SQLSQUAD.barrio AS B ON B.BARRIO_ID = DIR.DIRECCION_BARRIO_ID
	WHERE B.BARRIO_NOMBRE = M.INMUEBLE_BARRIO
	ORDER BY INMUEBLE_CODIGO